### PR TITLE
Closes #1521, fixes typo in between.Rd

### LINKED ISSUE #1521: A few improvements to between.Rd
- [ ] Need to uncomment `%`.
 - [ ] Need to mention the default value of `incbounds` is `TRUE` for the `x %between% y` infix usage.
 - [ ] Clarifying valid `x` `class`es (since `between` doesn't work with, e.g., `complex` or `factor` vectors)

### PR DESCRIPTION
**Pull request by MichaelChirico**
Basically identical to #1515; with perfect foresight these would have been the same PR.

### CODE REVIEW

**Comment by arunsrinivasan** [comment]
Could you please make changes specific to the issue you highlight? There's no ambiguity in the documentation as far as I can tell. Also what's *orderable*? The spacing in the code section is also on purpose. Matt doesn't like spaces between argument and value.

**Comment by MichaelChirico** [comment]
@arunsrinivasan _orderable_ means `<=` etc. are valid.

See `3 + 2i < 1 + 3i` -- `complex` types are not orderable. More commonly, `factor(1) < factor(2)` is also outside the scope of `between`. I'll revert the spacing.

**Comment by arunsrinivasan** [comment]
I find that definition of `orderable` confusing. Where do you draw this definition from? The word doesn't exist in the dictionary. My first thought was if the vector can be ordered, i.e., if `order(x)` is valid..

Everything else makes sense. I'd suggest then to change to title of PR to "Improvements to between.Rd". This isn't just a typo fix, but quite a lot of nice improvements.

**Comment by MichaelChirico** [comment]
@arunsrinivasan then you're using a poor dictionary ;-) [OED definition 3](http://www.oed.com/view/Entry/132336?redirectedFrom=orderable#eid) strikes quite close to what I have in mind ("That may be arranged in a series." in case it's paywalled).

But your confusion is still valid -- I'll add a few words to make it more clear what we have in mind as valid `x`.

Revision coming up tonight/tomorrow...

**Comment by arunsrinivasan** [comment]
Hm, I see it [here](http://www.oxforddictionaries.com/definition/english/orderable) now. Note to self: don't rely on my mac's inbuilt dictionary.

Sure, no hurry. Take your time. Thanks!

**Comment by MichaelChirico** [comment]
@arunsrinivasan should be all set

**Comment by arunsrinivasan** [comment]
Looks great!

**Pull request merged**
