### PR TITLE
Add tests of forder NA/NaN behavior

### PR DESCRIPTION
**Pull request by MichaelChirico**
Also, all the `TODO`s here are now pulled into #2572, so removing them from the tests file (where they're less visible)

### CODE REVIEW

**Comment by MichaelChirico** [comment]
> they weren't just `dput(forder())` right?

They were :grimacing:

**Comment by jangorecki** [comment]
So just please examine if returned values are expected ones. Such methodology of adding tests does tests only that returned values will not change over time but not if they are correct. It happens few times to me that I pushed incorrect tests like that.

**Comment by MichaelChirico** [comment]
Thanks @jangorecki. I actually think current behavior is inconsistent:

```
x = data.table(r = c(6, 4, 2, NA, 1, NaN, 5, NaN, 9, 10, NA))

x[order(r, na.last = TRUE)]
#         r
#     <num>
#  1:     1
#  2:     2
#  3:     4
#  4:     5
#  5:     6
#  6:     9
#  7:    10
#  8:   NaN
#  9:   NaN
# 10:    NA
# 11:    NA
x[order(r, na.last = FALSE)]
#         r
#     <num>
#  1:    NA
#  2:    NA
#  3:   NaN
#  4:   NaN
#  5:     1
#  6:     2
#  7:     4
#  8:     5
#  9:     6
# 10:     9
# 11:    10
x[order(-r, na.last = TRUE)]
#         r
#     <num>
#  1:    10
#  2:     9
#  3:     6
#  4:     5
#  5:     4
#  6:     2
#  7:     1
#  8:   NaN
#  9:   NaN
# 10:    NA
# 11:    NA
x[order(-r, na.last = FALSE)]
#         r
#     <num>
#  1:    NA
#  2:    NA
#  3:   NaN
#  4:   NaN
#  5:    10
#  6:     9
#  7:     6
#  8:     5
#  9:     4
# 10:     2
# 11:     1
```

**Comment by jangorecki** [comment]
I renamed to WIP so it won't be yet merged, lets first agree on expected output.

**Comment by mattdowle** [comment]
Great discussion.  I think of the ordering of NA and NaN as different to the ordering of the finite numbers: if `na.last` is provided then `NA` and `NaN` are put at the beginning or the end in a fixed order such that `NA` is always at the end with `NaN` before the NA.
I installed both v1.9.8 and v1.11.8 and checked the results checked in this PR match the results then.  All good.  So for the reason of consistency over time, these tests look good to me.

**Pull request merged**
