### PR TITLE
Created CJ.dt - for cross joining two data.tables

### PR DESCRIPTION
**Pull request by stephlocke**
Done as separate code on the assumption that it can later be deprecated when better code is integrated into CJ to handle two data.tables

Was initially going to be a helper function in optiRum but getting it into data.table is much more preferable.  I've not included any unit tests as the difference is significant but please see [these testthat unit tests for it](https://github.com/stephlocke/optiRum/blob/master/tests/testthat/test-CJ.dt.R) I've written for the function

### CODE REVIEW

**Comment by MichaelChirico** [comment]
@skanskan I guess this is filed on the wrong issue tracker? 

https://github.com/lockedata/optiRum/issues

I see `CJ.dt` in the `NAMESPACE` so maybe install from dev?

**Comment by stephlocke** [comment]
Yes - I implemented this in optiRum initially and look forward to it being deprecated one day :)

**Comment by skanskan** [comment]
Anyway I'm getting the result I want with
myDT[,myvector, by=c("all columns")]                
It works well if my vector is constant.

**Comment by MichaelChirico** [comment]
Hmm I guess this is #1717

**Pull request closed without merging**
