### PR TITLE
optimized Rinherits

### LINKED ISSUE #3919: Rinherits short-circuit
It should only call R if it's an S4 object, otherwise it can use INHERITS.
It can also have an if for nanotime too to save calling R for nanotime.

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #3919

### CODE REVIEW

**Comment by mattdowle** [comment]
As expected and desired, the `eval()` branch is no longer covered.  Will leave it uncovered for this release and come back to it in future when we cover the remaining C uncovered lines. I put a TODO commment there that describes how to cover it.

**Comment by jangorecki** [comment]
looks good, but I think it make sense to fill a request for a better interface to S4 classes

**Comment by mattdowle** [comment]
By 'fill a request' you mean ask R core to do something?

**Comment by jangorecki** [comment]
yes

**Comment by mattdowle** [comment]
I'll leave that to you then.

**Pull request merged**
