### PR TITLE
Fix segfaults when assigning to list column

### LINKED ISSUE #4166: segmentation fault when unlisting in-place list column
reproducible example:

```
dt<-data.table(a=list(1:2, 1:3))
dt[, a:=unlist(a)]
dt
```
data.table version: 1.12.8

session info:

```
R version 3.6.2 (2019-12-12)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/openblas-base/libblas.so.3
LAPACK: /usr/lib/libopenblasp-r0.2.18.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.12.8 colorout_1.2-0    rmarkdown_2.0    

loaded via a namespace (and not attached):
[1] compiler_3.6.2  tools_3.6.2     htmltools_0.4.0 Rcpp_1.0.3      knitr_1.26      xfun_0.11       digest_0.6.23   rlang_0.4.2     evaluate_0.14  
```

### LINKED ISSUE #4667: Crash on replacing list column with numeric values
Consider the following minimal example:

```r
library(data.table)

dt <- data.table(id = 1:10)
dt2 <- dt[, .(id, close)]
dt2
```

User would expect a numeric `close` column in `dt` but unfortunately there's none but `dt2` will capture `close` function silently and make that column a list of the same `close` functions.

```r
dt3 <- data.table(id = 1:10, price = rnorm(10))
dt2[dt3, close := price, on = .(id)]
```

Then replacing the `close` columns with a numeric column in another data.table will cause crash:

```
 *** caught segfault ***
address 0x6, cause 'memory not mapped'

Traceback:
 1: `[.data.table`(dt2, dt3, `:=`(close, price), on = .(id))
 2: dt2[dt3, `:=`(close, price), on = .(id)]

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

This crash seems to only happen on Linux but not macOS as I tried on both platforms. Not sure if crashes on Windows.

If it does not crash, the outcome might be unexpected for many users:

```
> dt2                                                                                                          
       id                                                                 close
    <int>                                                                <list>
 1:     1  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 2:     2  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 3:     3  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 4:     4  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 5:     5  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 6:     6  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 7:     7  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 8:     8  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
 9:     9  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
10:    10  1.9046580,-2.7921368, 0.6122573,-1.4355704,-0.9884517, 1.0093862,...
```

### LINKED ISSUE #4678: R crashes when assigning a list with a matrix to a subset of a data.table
Assigning a list with a matrix to a subset of a data.table causes R to crash with the error message:

`*** caught segfault ***`
`  address 0x4, cause 'memory not mapped'`

I am using R 3.6.3 on platform x86_64-pc-linux-gnu. This happened both when using data.table 1.12.8 and 1.13.0.

Reproducible example:
`library(data.table)`

`y <- data.table(i=c(1:10), m=list(matrix(c(0.1:0,4), 2, 2)))`
`x <- list(matrix(c(1.1:1.4), 2, 2))`

Assignment without subsetting works:
`y[, m := x]`
`y[, "m"] <- x`

But when subsetting rows and performing the same operation R terminates after attempting to print the object
`y[i>6, m := x]`
`y`

`#` `Output of sessionInfo()`
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8       
 [4] LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8   
 [6] LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets 
[6] methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3

### LINKED ISSUE #4729: Segfault when attempting to replace a list-column with an atomic vector of incorrect length
Hello data.table team:

Here's a segfault that seems different from the other ones in current issues:
```
d <- data.table(a=1:3)
d[,b:=list(c(1,2))]  ## all ok
d
#   a   b
# 1: 1 1,2
# 2: 2 1,2
# 3: 3 1,2

d[,b:=rep(c(1,2),2)] ## yes, this is the wrong thing to do
d  ## but the consequence is a bit harsh
```

 *** caught segfault ***
address 0x4, cause 'memory not mapped'

R version 3.6.0 (2019-04-26) -- "Planting of a Tree"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

> library(data.table)
data.table 1.13.0 using 20 threads (see ?getDTthreads).  Latest news: r-datatable.com

### PR DESCRIPTION
**Pull request by tlapak**
Closes #4166 
Closes #4667
Closes #4678
Closes #4729

The issue there was unrelated to the unlisting. A minimal example that also segfaults is
```R
dt <- data.table(a=list(1:2, 3, 4))
dt[, a:=1:4]
```
Turns out when LHS is a list column and RHS isn't, no length checks were being made. I am slightly surprised by @MichaelChirico's result which was maybe even intended.

While testing my fix I noticed that subassigning a vector of correct length also segfaults:
```R
dt <- data.table(a=list(1:2, 3, 4))
dt[1:2, a:=1:2]
```
I see three possible ways of handling this:

1. Error out with a coercion error
2. Treat RHS as length 1 and replicate
3. Coerce to list by wrapping elements of RHS in list()

I opted for 3. because why not. It seems the most intuitive to me besides 1. But happy to change this if people disagree. Required 'some' abuse of the BODY macro in memrecycle...

### CODE REVIEW

**Comment by tlapak** [comment]
Uh, if I understand the code

**Comment by jangorecki** [comment]
Thanks for PR. Yes, every new line of C has to be reached for code coverage to be happy. We can always workout code coverage later on. Much more important to pass the CI checks.

**Comment by tlapak** [comment]
Cool, thanks for the explanation. And I will try not to fat finger the close button again.

**Comment by jangorecki** [comment]
> if I understand the Codecov report correctly, I need to add unit tests for raw and complex rhs and one that doesn't fit any of these types?

Yes, you understand correct. If you would push to Rdatatable org branch, it would be much easier for others to add those tests for you. If you cannot yet push branches to our org then @mattdowle should be able to invite you to members.

**Comment by tlapak** [comment]
I'm not a member so can't push to this repo. 

Also, sorry for the delay. My time is a bit more limited than usual atm. I've now added the missing unit tests and found and fixed a bug in the process. I'm sure there's a lesson in there somewhere.

**Pull request merged**
