### PR TITLE
closes #1489 -- between gains "upper" and "lower" options

### LINKED ISSUE #1489: More improvements to %between%
There are a few other improvements in line for `between`, but a very simple one is increasing the flexibility of `incbounds` to allow values `"upper"` (case: `x > lower & x <= upper`) and `"lower"` (case: `x >= lower & x < upper`).

(edit: just noticed in the comment in [between.R](https://github.com/Rdatatable/data.table/blob/master/R/between.R) that there's a clunky suggested workaround -- `# If we want non inclusive bounds with %between%, just +1 to the left, and -1 to the right (assuming integers)` -- of course this doesn't work if `x` is continuous)

I also think it's more natural for `between` to take a vector as a second argument (so we can pass stuff of the form `between(x, range(y), FALSE)`, but this would break existing code. Perhaps different infixes for different defaults? `%bw%` is default, `%bwx%` is `incbounds = FALSE` (e**x**clusive), `%bwu%` is `incbounds = "upper"`, and `%bwl%` is `incbounds == "lower"`.

Also, the documentation doesn't make clear that the default for `between` is to set `incbounds = TRUE` (though this should be clear through the example, it makes sense to write it out as well). It also doesn't include an example usage of `%between%` in the Usage section.

Proposed update:

```
between <- function(x, lower, upper, incbounds = TRUE)
{
  if(isTRUE(incbounds)) x >= lower & x <= upper
  elseif (incbounds == FALSE) x > lower & x < upper
  elseif (incbounds == "upper") x > lower & x <= upper
  elseif (incbounds == "lower") x >= lower & x < upper
  else stop("Valid arguments for incbounds are TRUE, FALSE, "upper", and "lower")
}
```

Or a mite more efficiently:

```
between <- function(x, lower, upper, incbounds = TRUE)
{
  if (!incbounds %in% list(TRUE, FALSE, "upper", "lower")) stop('Valid arguments for incbounds are TRUE, FALSE, "upper", and "lower"')
  (if ((inct <- incbounds == TRUE) | incbounds == "lower") `>=` else `>`)(x, lower) &
    (if (inct | incbounds == "upper") `<=` else `<`)(x, upper)
}
```

### PR DESCRIPTION
**Pull request by MichaelChirico**
I don't know what standard protocol is for having multiple pull requests out at once. I took the approach of making any changes from the current master version (so there's no overlap with the other PR). Don't know how this works exactly...

I took the liberty of adding `%bwx%` etc without any go-ahead, feel free to reject if this is overkill.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
@arunsrinivasan I've scaled back the PR to simply add `"upper"` and `"lower"` arguments to `between`

**Comment by arunsrinivasan** [comment]
I'm not convinced reg. these arguments yet.

**Comment by MichaelChirico** [comment]
@arunsrinivasan I think the argument is simple-- 1) it add useful functionality to an existing function 2) full backwards compatibility -- no update to syntax required for continuing to use older arguments and 3) this update actually runs _faster_ (marginally) on my machine for original arguments:

```
set.seed(0128019)
NN <- 5e6
DT <-
  data.table(x = rnorm(NN)
             )[ , paste0("y", 1:100) := 
                  lapply(integer(100), function(...) rnorm(NN))]


between1 <- function(x, lower, upper, incbounds = TRUE){
  if(incbounds) x>=lower & x<=upper
  else x>lower & x<upper
}

between2 <- function(x, lower, upper, incbounds = TRUE)
{
  if (!incbounds %in% list(TRUE, FALSE, "upper", "lower")) 
    stop('Valid arguments for incbounds are TRUE, FALSE, "upper", and "lower"')
  (if ((incl <- incbounds == TRUE) | incbounds == "lower") `>=` else `>`)(x, lower) &
    (if (incl | incbounds == "upper") `<=` else `<`)(x, upper)
}

upr <- rnorm(1)
lwr <- rnorm(1)

library(microbenchmark)

microbenchmark(times = 20,
               old = DT[between1(x, lwr, upr)],
               new = DT[between2(x, lwr, upr)])
```

On my machine here are the timings:

```
Unit: milliseconds
 expr      min       lq     mean   median       uq      max neval cld
  old 140.3458 142.0172 144.8484 144.1071 148.1599 151.4712    20   a
  new 138.3738 140.3188 144.1902 143.5915 147.3189 155.7240    20   a
```

**Comment by arunsrinivasan** [comment]
I just don't think it makes sense to add `>= and <`, `> and <=` etc.. in `between()`. It's scope is limited to (and should be) `>= & <=` / `> & <`. It's simpler and covers most common cases.

**Comment by MichaelChirico** [comment]
@arunsrinivasan fair enough.

How about my suggestions for #707?

If there's something to be done there in the short term, I'll put up a (separate) PR for that which incorporates the fixes to the man page.

**Comment by arunsrinivasan** [comment]
I think that'll be taken care of once I've had time to work on `foverlaps()` to not require keys. Not sure when though. Not working on it at the moment.

**Comment by MichaelChirico** [comment]
@arunsrinivasan Got it; in that case I'll just run a separate PR for the man fix. Coming up soon.

**Pull request closed without merging**
