### PR TITLE
rbindlist check warning downgraded to message

### PR DESCRIPTION
**Pull request by mattdowle**
To pass package `tatoo` for #3473.
It's a print not message() for the reason written in news item.
Extensive control option added with tests.

### CODE REVIEW

**Comment by jangorecki** [comment]
`REprintf` is to make R's message from C

**Comment by mattdowle** [comment]
@jangorecki `REprintf` prints on `stderr`. It doesn't do what R level `message()` does; e.g. it can't be suppressed with `suppressMessages()`.
However, `rbindlist()` could construct a call to `message()` and `eval()` that at C level though. Will try that.

**Comment by jangorecki** [comment]
@mattdowle good to know, it took me a while to find `REprintf` and now I hear it is not what I wanted.
You think we could turn that into a function? so we can use it whenever `message` is needed.
```c
eval(PROTECT(lang2(install("message"),PROTECT(ScalarString(mkChar(buff))))), R_GlobalEnv); UNPROTECT(2)
```

**Comment by mattdowle** [comment]
Making it a function would be good.  I was going to.  The tricky thing was that `Rprintf`, `REprintf`, `warning`, and `error` all take `...` variable argument list.  We'd want the new `message` to follow the same parameter signature so that we could use it the same way as we use warning and error; e.g.  `message("Column %d ['%s'] has a problem", int, char *)`.  I couldn't remember how to do that in C using `va_arg` so I just went with this way for now. Or we could create `void message(const char *)` that takes a fixed string like that. In this example in `rbindlist`, because the new option allows control of the message/warning/error,  that section is using `sprintf` first anyway.  But in general it would be nice to have `message()` as function.
Btw, being able to fetch an `option()` value from C worked out nicely. Saves having to pass the option value down from R and is much more convenient and robust.  I didn't know `GetOption()` was available in the R API at C level until recently.  Maybe we can use it more in other places.  For example,  there are some function where I wanted to add some verbose output but `verbose` hadn't been passed through from R level. We could wrap GetOption("datatable.verbose") into a C function `bool verbose()` and just be careful not to call that inside loops.

**Comment by jangorecki** [comment]
@mattdowle agree. We have one such case in `fastmean`.

**Pull request merged**
