### PR TITLE
add test from TODO list insuring dcast plays well with being imported

### PR DESCRIPTION
**Pull request by MichaelChirico**
This has been sitting in the TODO queue of `tests.Rraw` for a while:

> Add test for fixed bug #5519 - dcast returned error when a package imported data.table, but dint happen when "depends" on data.table. This is fixed (commit 1263 v1.9.3), but not sure how to add test.

I couldn't check the original issue (R Forge days), so I'm not 100% sure this captures the goal of the comment. But the infrastructure for building a mini-package within the test is the trickier part anyway and that's covered here.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Can't say I understand the AppVeyor/Travis results... I guess it must be related to permissions from creating/installing the package, then uninstalling and removing? `test.data.table()` works on my machine

**Comment by HughParsonage** [comment]
I think the best approach would be to create a genuinely separate minimal package, then add it to the drat repository and to `Suggests:` then attach it (conditionally) as normal.

**Comment by MichaelChirico** [comment]
Open to ideas; mainly filed the PR as an impetus for conversation. Not really sure how to interact with drat -- one potential problem with the current setup is that `data.table` is already loaded when `testDTimport`'s function is run. Not sure if that would mask potential reversions of the bug. Seems the way around that is to add tests to `testDTimport`; not sure if there'd be a way to trigger `testDTimport` to install & test itself from within `data.table` tests 🤔

**Comment by HughParsonage** [comment]
This is complicated but one solution would be to place the relevant test in the minimal package rather than here and run reverse dependency checks from `data.table`, to include the minimal package.

**Comment by mattdowle** [comment]
Nice try!!  But we can't go anywhere near things like calling `install.packages()` from tests. It just won't fly on CRAN. Very reasonably, no writes to the system allowed. If any writes happen they must happen to `tempfile()` and that's about it.  Imagine if the `install.packages()` worked but then the test failed or crashed unexpectedly before the `remove.packages()`. How would the write to the library get cleaned up in that case?  I recently learnt in #2546 that CRAN's library is now mounted read-only, too, which seems like a good thing, hence the `testDir()` addition to avoid even just `setwd()` to library.

@HughParsonage's thought should fly. There is one test package already (DtNonAsciiTests) in the level up, here: https://github.com/Rdatatable. This test could be added there and that package's name changed to something more general (like DtExtraTests?).  We never got to finishing off that package.  IIRC the idea was it had tests that could not live on CRAN due to non-ASCII characters in test files which are not allowed (just on Mac iirc).  Maybe that could be overcome now, with fresh eyes.

Closing for now to be started again in DtExtraTests package or similar.

**Comment by MichaelChirico** [comment]
@mattdowle cool, I always wondered what the `DtNonAsciiTests` repository was about. Agreed it could serve more general testing purposes as well.

**Pull request closed without merging**
