### PR TITLE
Typo/grammar changes in datatable-programming vignette

### PR DESCRIPTION
**Pull request by tonyfischetti**
I corrected some typos/grammar of the new programming on data.table vignette.

One non-typo/grammar change I made (which, of course, I'm open to reverting) was to avoid a direct value comparison between this and other third-party packages that approach this problem. Best to just focus on data.table :)

With everybody's permission, I'd also like to clear up some of the diction in the section "Substituting lists of arbitrary length"
in a future pull request.

Thanks to @jangorecki for this great added feature!

### CODE REVIEW

**Comment by tonyfischetti** [comment]
Oh my, I see a similar pull request was submitted by @avimallu just a few hours ago.
There are some changes here that are not in that one. I can rebase the changes here
of on top of those commits if they get merged.

**Comment by tonyfischetti** [comment]
> @tonyfischetti, your changes are a lot more comprehensive. I can close my PR in favour of yours too if that works.

Sure :) If you'd like to

**Comment by mattdowle** [comment]
Thanks all! Will wait for @jangorecki to approve before merging.

**Comment by jangorecki** [comment]
Looks very good!

**Pull request merged**
