### PR TITLE
implements #1482: adds option to print.data.table to exclude lower register of column names when printing more than 20 rows

### PR DESCRIPTION
**Pull request by MichaelChirico**
also updated the R-Forge issue number to the corresponding GitHub issue number. Not sure if that's kosher...

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I guess we could make this more flexible with `col.names = "both"` by default and options for `"upper"`, `"lower"`, and `"none"`. This would definitely require adding a man page for `print.data.table`, but that may be inevitable anyway if we fill #645.

**Comment by arunsrinivasan** [comment]
`col.names` = "auto", "top" and "none" seems better to me.

Auto = current behaviour
top = only on top = data.frame like
none = no col names

?

On man page, I'd be happy to review the PR.

**Comment by MichaelChirico** [comment]
@arunsrinivasan it's not clear the desired behavior in the `"none"` case...

Do we expect simply a blank line or to exclude that line entirely (it's not immediately clear to me that the latter is possible)

The problem is encapsulated by `m <- rbind(1:2)`

Do we expect:

```
        #(the former, basically set `colnames` to `""`)
1 1 2
```

Or

```
1 1 2 #completely exclude the newline, perhaps can be done with `capture.output`?
```

**Comment by arunsrinivasan** [comment]
I'm not aware of the problem you mention, but my thought was to simply remove the line(s) containing column names entirely.

**Pull request closed without merging**
