### PR TITLE
Restore comma-separated columns to by= and key=

### PR DESCRIPTION
**Pull request by MichaelChirico**
As discussed in #4357, there's not an urgent need to break back-compatibility here. We might reconsider for data.table 2.0.

This PR restores the functionality removed by #6047, and adds a helper function to at least have a unified approach across the 3 call sites.

We don't need to revert / undo any of the suggested changes to downstream packages -- it's still a good practice to use the character vector approach in package code, and we mainly maintain the "CSV" approach as a convenience for interactive usage.

### CODE REVIEW

**Comment by tdhock** [comment]
there are 10 revdeps that fail because of https://github.com/Rdatatable/data.table/pull/6047
[zeitgebr](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/zeitgebr.txt)
[tidyfst](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/tidyfst.txt)
[tidyfast](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/tidyfast.txt)
[pointdensityP](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/pointdensityP.txt)
[maditr](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/maditr.txt)
[ggPMX](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/ggPMX.txt)
[expss](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/expss.txt)
[damr](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/damr.txt)
[calmr](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/calmr.txt)
[DramaAnalysis](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/DramaAnalysis.txt)
[BTYDplus](https://rcdata.nau.edu/genomic-ml/data.table-revdeps/analyze/2024-04-05/BTYDplus.txt)

**Comment by MichaelChirico** [comment]
Just filed fix PRs with all the downstreams that host their code on GitHub (all but  {pointdensityP}) for which a simple regex search identified some issues. More might remain e.g. in cases like `key="a,b,c"; data.table(key = key)` which are harder to identify.

**Comment by MichaelChirico** [comment]
OK, updated this PR to be a reversion to bring back 1.15.0 behavior. Thanks @HughParsonage for pushing back on the breaking change :)

**Review by tdhock — APPROVED** [review]
this is fine with me, thanks

**Pull request merged**
