### PR TITLE
Avoided GenomicRanges by writing known results to .Rdata, #2726

### LINKED ISSUE #2726: move GenomicRanges to integration tests
Currently installing suggested dependency GenomicRanges requires in total 11 packages to be installed, including one 17MB package. To keep testing process tiny we need to handle foverlaps tests without GenomicRanges.
Related: https://github.com/Rdatatable/data.table/issues/2740

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #2726 `
Current problems in #2767 point towards GenomicRanges or its dependencies. Removing it, as we wanted to do anyway, might help.

### CODE REVIEW

**Comment by jangorecki** [comment]
I would avoid keeping binary data in git but use csv instead but we can amend that after release.

**Comment by mattdowle** [comment]
Why avoid .Rdata?  With .Rdata the object types and attributes are retained; it's easier.

**Comment by jangorecki** [comment]
diff, git diff, head, etc. are not useful for binary data. Binary files are products, while in git (and other version control) it is best to keep sources, like code to produce binary files, or substitute like csv.

**Comment by mattdowle** [comment]
Saw this again on 32bit. Confirms it's not to do with GenomicRanges then : 
```
Running test id 1894.3      
  Running test id 1894.4      Error: memory exhausted (limit reached?)
  Error: memory exhausted (limit reached?)
  Execution halted
```

**Comment by MichaelChirico** [comment]
made it 200 tests further at least 😅

**Comment by mattdowle** [comment]
Merging despite `memory exhausted` error, as that's a different issue : #2767

**Pull request merged**
