### PR TITLE
update pkgdown config for non-dev branch

### PR DESCRIPTION
**Pull request by jangorecki**
remove pkgdown dev-mode leftovers

### CODE REVIEW

**Comment by jangorecki** [comment]
deployed: https://rdatatable.gitlab.io/data.table/

**Comment by MichaelChirico** [comment]
Thanks again @hadley for the support & encouragement!

**Comment by hadley** [comment]
You’re very welcome! (Btw it looks like the cheatsheet thumbnail isn’t working, at least not for me on mobile safari)

**Comment by MichaelChirico** [comment]
Same for me... have noted in #3883

**Pull request merged**
