### PR TITLE
install less in travis

### PR DESCRIPTION
**Pull request by jangorecki**
https://github.com/Rdatatable/data.table/pull/4164#issuecomment-572861920

### CODE REVIEW

**Comment by MichaelChirico** [comment]
LGTM! Forgot about when `covr` broke & we did this

**Comment by jangorecki** [comment]
stringi issue is here: https://github.com/gagolews/stringi/issues/366

it would probably be best to clarify why stringi is required for R travis-ci in https://travis-ci.community/c/languages/r but this forum won't let you to sign up using email but requires you to grant auth to your private github info.

**Comment by MichaelChirico** [comment]
Luckily I don't mind :)

https://travis-ci.community/t/why-is-stringi-required-for-travis-ci/6800?u=michaelchirico

**Comment by mattdowle** [comment]
This looks good to remove devtools from our travis.yml. So merging PR.  But it seems the stringi dependency is still there somehow and this PR isn't passing. Where's the dependency on stringi then: covr?

**Comment by MichaelChirico** [comment]
the Travis forum thread suggests clearing our cache?

**Comment by MichaelChirico** [comment]
yes, covr->rex->stringe->stringi

**Pull request merged**
