### PR TITLE
Spanish translations

### PR DESCRIPTION
**Pull request by rikivillalba**
Add "es.po" and "R-es.po" spanish translations
Relevant thread:
https://github.com/Rdatatable/data.table/pull/6199#issuecomment-2261825742

### CODE REVIEW

**Comment by MichaelChirico** [comment]
excellent! could you update the NEWS as well?

**Comment by MichaelChirico** [comment]
I've also invited you to become a Member of the repo, that will make it easier to create branches directly in this repo in the future. Welcome!

**Comment by MichaelChirico** [comment]
Translations pass my minimal QA checks (all messages translated, `checkPoFile()` passes, marked as UTF-8) 🎉 

cc @Rdatatable/spanish members who could maybe do a pass as reviewers of translations _per se_?

**Comment by rikivillalba** [comment]
> cc @Rdatatable/spanish members who could maybe do a pass as reviewers of translations _per se_?

Si es del interés de algun miembro del equipo comparto un archivo en formato de columnas con las traducciones para facilitar la comparación
I'm sharing translations in a tabular format, it may be of interest of members of @Rdatatable/spanish for ease of comparision

Regards!  
[Rdatatable translations.txt](https://github.com/user-attachments/files/16513790/Rdatatable.translations.txt)

**Comment by MichaelChirico** [comment]
I'll go ahead and merge, other translators feel free to file a follow-up with copy-edits to the translations if you see fit!

**Comment by rikivillalba** [comment]
Hello @MichaelChirico, neither spanish not portuguese translations seen in data.table/inst/po, these are going to be included in a release rigth?

**Pull request merged**
