### PR TITLE
Replace current data.table logo svg and png files

### LINKED ISSUE #6402: data.table logo not fully vectorized - poor reproduction quality
The data.table logo appears pixelated in areas and, depending on the format viewed, some cosmetic "blemishes" are present (e.g., vertical lines between shapes that make up the brackets/table legs).

On inspection of the .svg from the .graphics directory it appears that a raster image is embedded in the file, which is used for the lines of the seal. This results in difficulties rescaling the image without loss of quality, and the embedded image itself is not high quality. This explains the apparent pixelation. 

datatable_embeddedimg

I have created a fully vectorized version using InkScape that also addresses some of the disconnected shapes. This image should be able to be submitted for things like sticker printing without potential for quality issues--at least on the end of the supplied image. I was nudged to do a PR by @TysonStanley, which I'll be submitting soon. If any changes to the new logo are needed I'll be happy to complete them. Let me know if I should include the updated logo here as well, or if in the PR itself suffices

Thanks!

### PR DESCRIPTION
**Pull request by jmrung**
The original data.table logo is not fully vectorized. This PR is to replace the existing .svg and .png files with an updated version in which all elements are vectorized and hopefully easier to modify and navigate for any future edits needed.

Closes #6402

### CODE REVIEW

**Comment by TysonStanley** [comment]
LGTM! Thanks @jmrung!

**Review by TysonStanley — APPROVED** [review]

**Comment by tdhock** [comment]
this looks great, thanks!
can you please explain how you did that? did you manually retrace the lines with a mouse in inkscape/etc or did you use some more automatic bitmap to vector image conversion tool?

**Comment by tdhock** [comment]
also @jmrung for a follow up, if you have any time/interest, could you please consider volunteering to update the translation team logos https://github.com/Rdatatable/data.table/pull/6222#issuecomment-2216619506 ? (although as Micheal observed, when those translation team logos are displayed as small icons on github pages like https://github.com/orgs/Rdatatable/teams/brazil we don't actually see the pixelation of the seal; it may be useful if the logos are ever used in other contexts though -- presentations etc)

**Comment by MichaelChirico** [comment]
Looks great, thanks! Also love the GitHub tooling here for different ways to visualize the diff of an image 😎

**Comment by jmrung** [comment]
You’re very welcome! 

>if you have any time/interest, could you please consider volunteering to update the translation team logos https://github.com/Rdatatable/data.table/pull/6222#issuecomment-2216619506 ?

I can definitely help out with those logos, but might not be able to do so for a couple weeks. Let me know if there’s any issues with that timeline. Otherwise I'll check back in once I have them put together :)

> can you please explain how you did that? did you manually retrace the lines with a mouse in inkscape/etc or did you use some more automatic bitmap to vector image conversion tool?

Absolutely! I first opened the original seal in [GIMP](https://www.gimp.org/) and played with some filters to smooth out and crisp up the lines a little bit. Then I pasted it back into Inkscape. I started off by using the [“trace bitmap” tool](https://inkscape.org/doc/tutorials/tracing/tutorial-tracing.html) to get the rough shape of the seal, and then did a lot of manual editing to reduce the number of nodes on the paths and make it better resemble the original. I manually created the geometric parts; brought the “standard” hex shape into the image; and then added the text in, which I later saved as a path*. There’s a hidden layer where the text is still text, but having it as a path keeps it readable as-is in case the individual viewing doesn’t have the font on their device.  

*I actually didn’t realize there was an existing svg file when I started working on the updates—I was pointed to it later, so I probably would’ve skipped fully recreating some of the elements had that been the case.

**Comment by tdhock** [comment]
thanks for the detailed explanation. I did not know about the trace bitmap tool. A couple of weeks is fine, thanks for volunteering!

**Pull request merged**
