### PR TITLE
Clarify documentation

### PR DESCRIPTION
**Pull request by gwerbin**
Specifies that the correct syntax for "on = " is "on = c(name_in_x = name_in_i)", and documents the "i.name" prefixing behavior in joins. Closes https://github.com/Rdatatable/data.table/issues/1038

### CODE REVIEW

**Comment by arunsrinivasan** [comment]
Thanks. But could you please update with just the issue you're issuing a fix for -- the "i." prefix?

Also, the explanation should go in `j`. A separate paragraph in `j` section and some examples would be great.

**Comment by gwerbin** [comment]
Meaning, make separate pull requests for the two issues?

**Comment by arunsrinivasan** [comment]
@gwerbin yes.

Since you're expanding on `on=`, I'd suggest that you explain it in detail. Instead of "of the form ...", i.e., something like: "Suppose the data.tables x and y have cols 'a,b' and 'c,d' and we would like to join on x's col a with y's column c, then we can do x[y, on=c(a = "c")]" 

Like the expansion of the examples very much.

**Comment by gwerbin** [comment]
Okay, I can be more explicit in that example. I'll try to figure out how to make a PR with just a single commit and re-submit both.

Also, has the `y.1` syntax been phased out? I couldn't get it to work.

**Comment by gwerbin** [comment]
Also, I described `i.` in the section for `i=` and not `j=` because it seemed like a natural extension of the description of joining behavior, where columns in `i` not used for joining are passed into the result. Maybe I could mention it in both places? I'd rather be redundant for the sake of clarity, but I don't want to enforce my style on someone else's project.

**Comment by arunsrinivasan** [comment]
Just `j` is fine.

**Comment by gwerbin** [comment]
I made two separate pull requests: https://github.com/Rdatatable/data.table/pull/1329 and https://github.com/Rdatatable/data.table/pull/1328

**Comment by franknarf1** [comment]
@gwerbin  The `y.1` is alive and well. I saw it a few days ago here: http://stackoverflow.com/revisions/32527229/1

It looks like it's used just when you merge `X[Y]` where `X` has a column named `i.y` and `Y` has a column named `y`, in which case `X`'s `i.y` is renamed `i.y.1`. I don't know if such disambiguation needs to be documented (since it's a rare edge case), but it's great to see the `i.` thing there now. Thanks!

**Pull request closed without merging**
