### PR TITLE
 Add an "unsetkey" convenience function

### PR DESCRIPTION
**Pull request by gwerbin**
I pulled this one from my .Rprofile and just thought I'd share.

I sometimes find myself temporarily setting keys (e.g. before a join) and then removing them shortly afterwards. This is a convenience function intended mostly for that use, although it might be somewhat unnecessary now that we have the `on = ` argument. I specifically made sure that the original order of the remaining keys is preserved.

### CODE REVIEW

**Comment by arunsrinivasan** [comment]
The purpose of the function seems to have a shorter way of doing `setkey(dt, <all cols except these ones>)` IIUC. You can use `setdiff()` for that. I think the intent is clear in that manner. `unsetkey()` is a confusing name, when it's setting (different) keys.

**Comment by gwerbin** [comment]
@arunsrinivasan you mean, `setkey(dt, setdiff(key(dt), key_i_want_to_remove))`? Hadn't thought of that.

**Comment by arunsrinivasan** [comment]
Right. Perhaps a verb `except()` could work.. `setkey(dt, except(these_cols))`. Could be useful in `DT[i, j, by=except(these_cols)]` too..

**Comment by gwerbin** [comment]
@arunsrinivasan actually the `except` verb would also be great in `.SDcols=`

**Pull request closed without merging**
