### PR TITLE
Improves diagnostic messaging of .SDcols when passed bad data

### LINKED ISSUE #3116: Improve error message when using missing column in .SDcols
Discovered when updating the source table in an ETL and using `data.table` downstream; source column names changed and gave me an error that's hard to deal with quickly:

```
DT = data.table(a = 1:5)
DT[ , .SD, .SDcols = 'b']
```

> Error in `[.data.table`(DT, , .SD, .SDcols = "b") : 
> Some items of .SDcols are not column names (or are NA)

### LINKED ISSUE #3118: Inconsistent .SDcols behavior NA vs. NA_character
Uncovered in work on #3116 

```
DT = data.table(a = 1:5)
DT[ , .SD, .SDcols = NA]
# Null data.table (0 rows and 0 cols)
DT[ , .SD, .SDcols = NA_character_]
```

> Error in `[.data.table`(DT, , .SD, .SDcols = NA_character_) : 
>   Some items of .SDcols are not column names (or are NA)

I guess should error in both cases...

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #3116 
Closes #3118 

Also added `brackify` helper function. Might consider using it wherever `collapse = ', '`-style error messages are used now...

### CODE REVIEW

**Comment by mattdowle** [comment]
Please put "closes #num" in the body, not in the title.

**Comment by mattdowle** [comment]
Looks like a true fail in R-devel on length comparison. Will leave to you.

**Comment by MichaelChirico** [comment]
@mattdowle finally got all the issues sorted out & managed to cover a bunch of new stuff in tests as well. ready to merge

**Comment by mattdowle** [comment]
Great PR!

**Pull request merged**
