### PR TITLE
print many columns does not reorder columns anymore, #3306

### LINKED ISSUE #3306: Column-reordered table printed when subsetting
I notice a strange behavior of `print.data.table` in latest release. When there's a large number of columns, printing a subsetted data.table will show a column-reordered table, but the result still have correct `colnames`.

```r
library(data.table)

dt <- data.table(id = 1:10000)
for (i in 1:300) {
  dt[, paste0("v", i) := rnorm(.N)]
}
dt[v100 >= 0]
```

image

```r
> colnames(dt[v100 >= 0])
  [1] "id"   "v1"   "v2"   "v3"   "v4"   "v5"   "v6"   "v7"   "v8"   "v9"   "v10"  "v11"  "v12"  "v13"  "v14"  "v15"  "v16"  "v17"  "v18"  "v19"  "v20"  "v21"  "v22"  "v23"  "v24" 
 [26] "v25"  "v26"  "v27"  "v28"  "v29"  "v30"  "v31"  "v32"  "v33"  "v34"  "v35"  "v36"  "v37"  "v38"  "v39"  "v40"  "v41"  "v42"  "v43"  "v44"  "v45"  "v46"  "v47"  "v48"  "v49" 
 [51] "v50"  "v51"  "v52"  "v53"  "v54"  "v55"  "v56"  "v57"  "v58"  "v59"  "v60"  "v61"  "v62"  "v63"  "v64"  "v65"  "v66"  "v67"  "v68"  "v69"  "v70"  "v71"  "v72"  "v73"  "v74" 
 [76] "v75"  "v76"  "v77"  "v78"  "v79"  "v80"  "v81"  "v82"  "v83"  "v84"  "v85"  "v86"  "v87"  "v88"  "v89"  "v90"  "v91"  "v92"  "v93"  "v94"  "v95"  "v96"  "v97"  "v98"  "v99" 
[101] "v100" "v101" "v102" "v103" "v104" "v105" "v106" "v107" "v108" "v109" "v110" "v111" "v112" "v113" "v114" "v115" "v116" "v117" "v118" "v119" "v120" "v121" "v122" "v123" "v124"
[126] "v125" "v126" "v127" "v128" "v129" "v130" "v131" "v132" "v133" "v134" "v135" "v136" "v137" "v138" "v139" "v140" "v141" "v142" "v143" "v144" "v145" "v146" "v147" "v148" "v149"
[151] "v150" "v151" "v152" "v153" "v154" "v155" "v156" "v157" "v158" "v159" "v160" "v161" "v162" "v163" "v164" "v165" "v166" "v167" "v168" "v169" "v170" "v171" "v172" "v173" "v174"
[176] "v175" "v176" "v177" "v178" "v179" "v180" "v181" "v182" "v183" "v184" "v185" "v186" "v187" "v188" "v189" "v190" "v191" "v192" "v193" "v194" "v195" "v196" "v197" "v198" "v199"
[201] "v200" "v201" "v202" "v203" "v204" "v205" "v206" "v207" "v208" "v209" "v210" "v211" "v212" "v213" "v214" "v215" "v216" "v217" "v218" "v219" "v220" "v221" "v222" "v223" "v224"
[226] "v225" "v226" "v227" "v228" "v229" "v230" "v231" "v232" "v233" "v234" "v235" "v236" "v237" "v238" "v239" "v240" "v241" "v242" "v243" "v244" "v245" "v246" "v247" "v248" "v249"
[251] "v250" "v251" "v252" "v253" "v254" "v255" "v256" "v257" "v258" "v259" "v260" "v261" "v262" "v263" "v264" "v265" "v266" "v267" "v268" "v269" "v270" "v271" "v272" "v273" "v274"
[276] "v275" "v276" "v277" "v278" "v279" "v280" "v281" "v282" "v283" "v284" "v285" "v286" "v287" "v288" "v289" "v290" "v291" "v292" "v293" "v294" "v295" "v296" "v297" "v298" "v299"
[301] "v300"
```

### PR DESCRIPTION
**Pull request by jangorecki**
Closes #3306 
Follow up in #3373
This PR fixes the print method by using `rbindlist` instead of `rbind`.

### CODE REVIEW

**Comment by mattdowle** [comment]
Could you explain what the root cause of the problem is please. Is using `rbindlist` a workaround? Why doesn't `rbind` work?  Is the root cause fixed?

**Comment by jangorecki** [comment]
even when we will fix `rbind` issue, this PR make sense, as `rbind` calls `rbindlist` anyway.

**Comment by mattdowle** [comment]
I can reproduce the problem with `rbindlist` too though.  It's a random result.  I don't see how calling `rbindlist` directly helps.
```
> names(rbindlist(list(a,a)))
  [1] "V1"   "V2"   "V3"   "V4"   "V5"   "V6"   "V7"   "V8"   "V9"   "V10"  "V11"  "V12"  "V13"  "V14"  "V15"  "V16"  "V17"  "V18"  "V19"  "V20"  "V21"  "V22"  "V23"  "V24"  "V25"  "V26"  "V27" 
 [28] "V28"  "V29"  "V30"  "V31"  "V32"  "V33"  "V34"  "V35"  "V36"  "V37"  "V38"  "V39"  "V40"  "V41"  "V42"  "V43"  "V44"  "V45"  "V46"  "V47"  "V48"  "V49"  "V50"  "V51"  "V52"  "V53"  "V54" 
 [55] "V55"  "V56"  "V57"  "V58"  "V59"  "V60"  "V61"  "V62"  "V63"  "V64"  "V65"  "V66"  "V67"  "V68"  "V69"  "V70"  "V71"  "V72"  "V73"  "V74"  "V75"  "V76"  "V77"  "V78"  "V79"  "V80"  "V81" 
 [82] "V82"  "V83"  "V84"  "V85"  "V86"  "V87"  "V88"  "V89"  "V90"  "V91"  "V92"  "V93"  "V94"  "V95"  "V96"  "V97"  "V98"  "V99"  "V100" "V101" "V102" "V103" "V104" "V105" "V106" "V107" "V108"
[109] "V109" "V110" "V111" "V112" "V113" "V114" "V115" "V116" "V117" "V118" "V119" "V120" "V121" "V122" "V123" "V124" "V125" "V126" "V127" "V128" "V129" "V130" "V131" "V132" "V133" "V134" "V135"
[136] "V136" "V137" "V138" "V139" "V140" "V141" "V142" "V143" "V144" "V145" "V146" "V147" "V148" "V149" "V150" "V151" "V152" "V153" "V154" "V155" "V156" "V157" "V158" "V159" "V160" "V161" "V162"
[163] "V163" "V164" "V165" "V166" "V167" "V168" "V169" "V170" "V171" "V172" "V173" "V174" "V175" "V176" "V177" "V178" "V179" "V180" "V181" "V182" "V183" "V184" "V185" "V186" "V187" "V188" "V189"
[190] "V190" "V191" "V192" "V193" "V194" "V195" "V196" "V197" "V198" "V199" "V200" "V201" "V202" "V203" "V204" "V205" "V206" "V207" "V208" "V209" "V210" "V211" "V212" "V213" "V214" "V215" "V216"
[217] "V217" "V218" "V219" "V220" "V221" "V222" "V223" "V224" "V225" "V226" "V227" "V228" "V229" "V230" "V231" "V232" "V233" "V234" "V235" "V236" "V237" "V238" "V239" "V240" "V241" "V242" "V243"
[244] "V244" "V245" "V246" "V247" "V248" "V249" "V250" "V251" "V252" "V253" "V254" "V255"
> 
> names(rbindlist(list(a,a), TRUE))
  [1] "V1"   "V194" "V195" "V2"   "V3"   "V4"   "V5"   "V6"   "V7"   "V8"   "V9"   "V138" "V139" "V10"  "V11"  "V75"  "V74"  "V12"  "V13"  "V14"  "V15"  "V16"  "V17"  "V200" "V201" "V18"  "V19" 
 [28] "V20"  "V21"  "V22"  "V23"  "V76"  "V77"  "V24"  "V25"  "V26"  "V27"  "V28"  "V29"  "V30"  "V31"  "V32"  "V33"  "V34"  "V35"  "V36"  "V37"  "V216" "V217" "V153" "V152" "V38"  "V39"  "V40" 
 [55] "V41"  "V42"  "V43"  "V44"  "V45"  "V46"  "V47"  "V107" "V106" "V108" "V109" "V48"  "V49"  "V160" "V161" "V227" "V226" "V50"  "V51"  "V52"  "V53"  "V54"  "V55"  "V56"  "V57"  "V228" "V229"
 [82] "V58"  "V59"  "V60"  "V61"  "V239" "V238" "V62"  "V63"  "V64"  "V65"  "V172" "V173" "V66"  "V67"  "V134" "V135" "V193" "V192" "V68"  "V69"  "V196" "V197" "V70"  "V71"  "V72"  "V73"  "V78" 
[109] "V79"  "V149" "V148" "V80"  "V81"  "V82"  "V83"  "V209" "V208" "V84"  "V85"  "V214" "V215" "V86"  "V87"  "V88"  "V89"  "V90"  "V91"  "V92"  "V93"  "V94"  "V95"  "V96"  "V97"  "V223" "V222"
[136] "V98"  "V99"  "V100" "V101" "V102" "V103" "V104" "V105" "V157" "V156" "V110" "V111" "V112" "V113" "V114" "V115" "V116" "V117" "V168" "V169" "V118" "V119" "V120" "V121" "V122" "V123" "V240"
[163] "V241" "V124" "V125" "V126" "V127" "V128" "V129" "V182" "V183" "V130" "V131" "V132" "V133" "V136" "V137" "V140" "V141" "V142" "V143" "V144" "V145" "V205" "V204" "V146" "V147" "V206" "V207"
[190] "V150" "V151" "V219" "V218" "V154" "V155" "V158" "V159" "V162" "V163" "V224" "V225" "V164" "V165" "V166" "V167" "V170" "V171" "V174" "V175" "V176" "V177" "V178" "V179" "V180" "V181" "V244"
[217] "V245" "V184" "V185" "V186" "V187" "V188" "V189" "V190" "V191" "V255" "V254" "V198" "V199" "V202" "V203" "V210" "V211" "V212" "V213" "V220" "V221" "V230" "V231" "V232" "V233" "V234" "V235"
[244] "V236" "V237" "V242" "V243" "V246" "V247" "V248" "V249" "V250" "V251" "V252" "V253"
> 
> names(rbindlist(list(a,a), use.names=TRUE))
  [1] "V1"   "V5"   "V4"   "V2"   "V3"   "V74"  "V75"  "V6"   "V7"   "V8"   "V9"   "V10"  "V11"  "V140" "V141" "V12"  "V13"  "V202" "V203" "V14"  "V15"  "V88"  "V89"  "V16"  "V17"  "V18"  "V19" 
 [28] "V20"  "V21"  "V96"  "V97"  "V22"  "V23"  "V24"  "V25"  "V26"  "V27"  "V28"  "V29"  "V104" "V105" "V30"  "V31"  "V32"  "V33"  "V34"  "V35"  "V106" "V107" "V232" "V233" "V36"  "V37"  "V236"
 [55] "V237" "V38"  "V39"  "V40"  "V41"  "V244" "V245" "V42"  "V43"  "V246" "V247" "V44"  "V45"  "V188" "V189" "V192" "V193" "V46"  "V47"  "V48"  "V49"  "V50"  "V51"  "V52"  "V53"  "V54"  "V55" 
 [82] "V56"  "V57"  "V58"  "V59"  "V60"  "V61"  "V62"  "V63"  "V64"  "V65"  "V124" "V125" "V66"  "V67"  "V195" "V194" "V68"  "V69"  "V70"  "V71"  "V72"  "V73"  "V135" "V134" "V76"  "V77"  "V78" 
[109] "V79"  "V80"  "V81"  "V82"  "V83"  "V84"  "V85"  "V142" "V143" "V86"  "V87"  "V90"  "V91"  "V92"  "V93"  "V94"  "V95"  "V145" "V144" "V98"  "V99"  "V100" "V101" "V102" "V103" "V167" "V166"
[136] "V108" "V109" "V110" "V111" "V112" "V113" "V114" "V115" "V238" "V239" "V116" "V117" "V249" "V248" "V118" "V119" "V191" "V190" "V120" "V121" "V122" "V123" "V126" "V127" "V128" "V129" "V130"
[163] "V131" "V132" "V133" "V136" "V137" "V200" "V201" "V138" "V139" "V204" "V205" "V146" "V147" "V148" "V149" "V150" "V151" "V213" "V212" "V152" "V153" "V154" "V155" "V156" "V157" "V158" "V159"
[190] "V160" "V161" "V162" "V163" "V164" "V165" "V168" "V169" "V170" "V171" "V172" "V173" "V174" "V175" "V176" "V177" "V178" "V179" "V234" "V235" "V180" "V181" "V182" "V183" "V184" "V185" "V186"
[217] "V187" "V196" "V197" "V198" "V199" "V206" "V207" "V208" "V209" "V210" "V211" "V214" "V215" "V216" "V217" "V218" "V219" "V220" "V221" "V222" "V223" "V224" "V225" "V226" "V227" "V228" "V229"
[244] "V230" "V231" "V240" "V241" "V242" "V243" "V250" "V251" "V252" "V253" "V254" "V255"
>
> names(rbindlist(list(a,a), use.names=TRUE))
  [1] "V1"   "V2"   "V3"   "V4"   "V5"   "V6"   "V7"   "V8"   "V9"   "V205" "V204" "V10"  "V11"  "V206" "V207" "V211" "V210" "V12"  "V13"  "V212" "V213" "V134" "V135" "V14"  "V15"  "V16"  "V17" 
 [28] "V18"  "V19"  "V20"  "V21"  "V214" "V215" "V22"  "V23"  "V24"  "V25"  "V149" "V148" "V26"  "V27"  "V28"  "V29"  "V30"  "V31"  "V150" "V151" "V32"  "V33"  "V155" "V154" "V34"  "V35"  "V36" 
 [55] "V37"  "V103" "V102" "V38"  "V39"  "V40"  "V41"  "V42"  "V43"  "V44"  "V45"  "V176" "V177" "V46"  "V47"  "V48"  "V49"  "V181" "V180" "V50"  "V51"  "V52"  "V53"  "V54"  "V55"  "V56"  "V57" 
 [82] "V58"  "V59"  "V182" "V183" "V60"  "V61"  "V62"  "V63"  "V64"  "V65"  "V186" "V187" "V66"  "V67"  "V68"  "V69"  "V70"  "V71"  "V203" "V202" "V72"  "V73"  "V133" "V132" "V74"  "V75"  "V137"
[109] "V136" "V76"  "V77"  "V78"  "V79"  "V216" "V217" "V219" "V218" "V80"  "V81"  "V138" "V139" "V141" "V140" "V82"  "V83"  "V220" "V221" "V84"  "V85"  "V225" "V224" "V86"  "V87"  "V142" "V143"
[136] "V145" "V144" "V88"  "V89"  "V90"  "V91"  "V146" "V147" "V92"  "V93"  "V152" "V153" "V94"  "V95"  "V96"  "V97"  "V98"  "V99"  "V100" "V101" "V241" "V240" "V104" "V105" "V242" "V243" "V245"
[163] "V244" "V106" "V107" "V108" "V109" "V110" "V111" "V112" "V113" "V114" "V115" "V246" "V247" "V116" "V117" "V167" "V166" "V118" "V119" "V120" "V121" "V122" "V123" "V124" "V125" "V126" "V127"
[190] "V128" "V129" "V130" "V131" "V156" "V157" "V158" "V159" "V160" "V161" "V162" "V163" "V238" "V239" "V164" "V165" "V168" "V169" "V170" "V171" "V172" "V173" "V174" "V175" "V178" "V179" "V255"
[217] "V254" "V184" "V185" "V188" "V189" "V190" "V191" "V192" "V193" "V194" "V195" "V196" "V197" "V198" "V199" "V200" "V201" "V208" "V209" "V222" "V223" "V226" "V227" "V228" "V229" "V230" "V231"
[244] "V232" "V233" "V234" "V235" "V236" "V237" "V248" "V249" "V250" "V251" "V252" "V253"
> 
```

There's far too much complexity at the top of rbindlist.c. It need chopping back and simplifying. There's no need for any hashing.

**Comment by MichaelChirico** [comment]
Right... a fix is to set `use.names = FALSE` since there's no attempt to reorder then. But fixing `rbindlist` is better.

**Comment by mattdowle** [comment]
Ok now I see why this PR fixes the print issue. Via `rbind` sets `use.names=TRUE` but `rbindlist`'s default is `use.names=FALSE`.

**Pull request merged**
