### PR TITLE
Remove {UN,}SET_S4_OBJECT usage

### PR DESCRIPTION
**Pull request by MichaelChirico**
Part of #6180.

I would like to test the dogroups change. I don't _think_ there's any reason to do `UNSET_S4_OBJECT()`? How could the object wound up marked as S4?

Certainly we pass tests as is. Can anyone come up with an example broken by this change? :thinking:

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Reading a tiny bit more carefully how `keepattr()` is used in dogroups, it's part of `growVector()`, in turn called twice:

https://github.com/Rdatatable/data.table/blob/ff900d1e6a8bcfaa0385bd1304af7b90657d3c4d/src/dogroups.c#L401
https://github.com/Rdatatable/data.table/blob/ff900d1e6a8bcfaa0385bd1304af7b90657d3c4d/src/dogroups.c#L449

That's for places where we need to mess with the group memory size because of bad estimates up-front (?). So IINM to be broken you'd need to be doing hard-to-predict grouping operations on S4 columns. But already messing with S4 columns in `j` has very limited support (see e.g. #4415). So it's not clear anyone would be affected.

**Comment by ben-schwen** [comment]
AFAIU `IS_S4_OBJECT` is also part of non exported API.

**Comment by MichaelChirico** [comment]
I don't think that's right, here it is in Rinternals:

https://github.com/r-devel/r-svn/blob/53bbd920926a6263bf0e870fa142c6171f37ec01/src/include/Rinternals.h#L273

Well above the "Not API" section

And here it's mentioned in R-ints as the "correct" way to test S4:

https://github.com/r-devel/r-svn/blob/53bbd920926a6263bf0e870fa142c6171f37ec01/doc/manual/R-ints.texi#L1397-L1401

**Comment by ben-schwen** [comment]
My bad, I should have the new section in [WRE](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Moving-into-C-API-compliance).

There we have it:
> This table lists some non-API functions used in packages and the API functions that should be used instead:
  IS_S4_OBJECT
  Use isObject and isS4.

**Comment by MichaelChirico** [comment]
Nice. Slightly confused why this is note showing up in our `NOTE` (yet?), and about the organization of the header & R-ints ref, but assume that'll be ironed out over time.

**Comment by ben-schwen** [comment]
LGTM, but lets see what revdeps will say

**Pull request merged**
