### PR TITLE
docs: seal of approval entry for mlr3

### PR DESCRIPTION
**Pull request by m-muecke**

### CODE REVIEW

**Comment by tdhock** [comment]
hi @m-muecke thanks for your PR. 
I believe mlr3 is a great candidate to obtain the Seal of Approval.
However before we merge this PR, please first follow these instructions: 

To add your package to this list, please [submit a Pull Request to The Raft](https://github.com/rdatatable-community/The-Raft/), making sure to follow the templated instructions:  https://github.com/rdatatable-community/The-Raft/blob/main/.github/PULL_REQUEST_TEMPLATES/seal_of_approval.md

Basically you would just have to write a short blog which explains what mlr3 does, and how it relates to data.table, like these: https://rdatatable-community.github.io/The-Raft/#category=seal%20of%20approval

By the way, you are the first person who has submitted a package for the Seal of Approval, so we would appreciate any feedback you could share about how we could improve documentation for the submission process. For example, perhaps it would be helpful to directly link the templated instructions (https://github.com/rdatatable-community/The-Raft/blob/main/.github/PULL_REQUEST_TEMPLATES/seal_of_approval.md) from https://github.com/Rdatatable/data.table/blob/master/Seal_of_Approval.md ?

**Review by Anirban166 — APPROVED** [review]
LGTM!

**Comment by Anirban166** [comment]
Since we are also at the topic of improving this file, I'd like to suggest some slight formatting changes:

```md
# Seal of Approval

This is a list of packages in the `data.table` community.

Further detail about these packages and their relationship to `data.table` can be found at [The Raft blog](https://rdatatable-community.github.io/The-Raft/#category=seal%20of%20approval).

To add your package to this list, please [submit a Pull Request to The Raft](https://github.com/rdatatable-community/The-Raft/), making sure to follow the templated instructions.

## Extension packages
> Adds to the internal functionality of `data.table`.

- [nc](https://github.com/tdhock/nc): Named capture regular expressions for text parsing and data reshaping.

## Application packages
> Uses `data.table` to accomplish a particular task or analysis.

- [mlr3](https://github.com/mlr-org/mlr3): A versatile machine learning framework built on data.table.

## Bridge packages
> Translates `data.table` syntax to a different one or provides helper functions for transitioning between `data.table` and another object type.

- [tidyfast](https://github.com/TysonStanley/tidyfast): Fast and efficient alternatives to tidyr functions built on data.table

- [dtplyr](https://github.com/tidyverse/dtplyr): A `data.table` backend for `dplyr`

## Partner packages
> Not necessarily directly connected to `data.table`, but deliberately follows the [core philosophies of `data.table`](https://github.com/Rdatatable/data.table/blob/master/GOVERNANCE.md#the-r-package).
```

The changes above makes the document look like this on GitHub:

image
image


which I think might be a bit better for the appearance of the headings than the current look: (also, includes minor changes to the text like `packages` instead of `package` in two instances, taken from https://github.com/rdatatable-community/The-Raft/pull/43)

image

**Comment by tdhock** [comment]
> Since we are also at the topic of improving this file, I'd like to suggest some slight formatting changes:

please create a separate issue/pr

**Comment by Anirban166** [comment]
> > Since we are also at the topic of improving this file, I'd like to suggest some slight formatting changes:
> 
> please create a separate issue/pr

Sure! Should I wait till this gets merged though, to avoid conflict? (or just sync forks later on or merge the changes I suggested first?)

**Comment by Anirban166** [comment]
> > > Since we are also at the topic of improving this file, I'd like to suggest some slight formatting changes:
> > 
> > 
> > please create a separate issue/pr
> 
> Sure! Should I wait till this gets merged though, to avoid conflict? (or just sync forks later on or merge the changes I suggested first?)

Also, what about this? @tdhock 
(Should I create a PR for updating the Seal of Approval doc right now or wait till this gets merged?)

**Comment by tdhock** [comment]
no need to wait, please do it now

**Comment by Anirban166** [comment]
Sure, and yes I'll hide our comments (mark as 'off-topic') to avoid clutter

**Comment by kbodwin** [comment]
The draft post justifying this Seal is here: https://github.com/rdatatable-community/The-Raft/blob/main/posts/2024-09-24-seal_of_approval-mlr3/index.qmd

Once this PR is merged, I will make the post live!

**Comment by tdhock** [comment]
hi @m-muecke your blog looks great to me, thanks for your contribution!

**Pull request merged**
