### PR TITLE
Refactor colClasses handling for readability

### PR DESCRIPTION
**Pull request by MichaelChirico**
Towards #6105. This PR is a simple refactor to reduce code nesting / improve readability. It makes the actual implementation of #6105, #6107, much simpler.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
* **#6107** <a href="https://app.graphite.dev/github/pr/Rdatatable/data.table/6107?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#6106** <a href="https://app.graphite.dev/github/pr/Rdatatable/data.table/6106?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `master`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @MichaelChirico and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by MichaelChirico** [comment]
@Anirban166 any idea what's going on with the {atime} CI failure?

```
Error in value[[3L]](cond) : 
  Error in revparse_single(object, branch): Error in 'git2r_revparse_single': Requested object could not be found

 when trying to checkout 1872f473b20fdcddc5c1b35d79fe9229cd9a1d15
```

**Comment by Anirban166** [comment]
> @Anirban166 any idea what's going on with the {atime} CI failure?
> 
> ```
> Error in value[[3L]](cond) : 
>   Error in revparse_single(object, branch): Error in 'git2r_revparse_single': Requested object could not be found
> 
>  when trying to checkout 1872f473b20fdcddc5c1b35d79fe9229cd9a1d15
> ```

It appears that it is trying to install a `data.table` version that doesn't belong to any branch here: https://github.com/Rdatatable/data.table/commit/1872f473b20fdcddc5c1b35d79fe9229cd9a1d15

This was previously working for us since the `setdt-wide` branch existed, but now that it has been deleted, none of the commits within that PR would be valid since they are not a part of the current `data.table` repository (no branch, no references)

Also @tdhock I think this is why the last commits in some PRs don't work (because their branches have been deleted) but the merge commits work (because they are integrated or stay as a part of `data.table`)

**Comment by Anirban166** [comment]
@MichaelChirico I believe the easiest fix here would be to hit 'Restore branch' for `setdt-wide` towards the end of #5427 

(I've encountered this issue [before](https://github.com/Anirban166/Autocomment-atime-results/issues/27) and in that case too, the main reason had to do with certain branches being non-existent as I did a shallow fork of `data.table` and did not retrieve the entire set of branches and commits)

**Comment by MichaelChirico** [comment]
Hmm, I don't have any trouble running `git checkout 1872f473b20fdcddc5c1b35d79fe9229cd9a1d15` locally though...

**Comment by MichaelChirico** [comment]
OK, moved the above into its own issue to keep focused comments on this PR: #6110.

**Review by tdhock — APPROVED** [review]
I try to avoid continue in my personal code "for readability" but you are right it helps in this case.
I looked at the rest of the code base to make sure continue is used elsewhere, and it is used quite a lot

**Comment by MichaelChirico** [comment]
Some more changes here, mainly to rename some variables/add comments for readability.

**Comment by tdhock** [comment]
please try to avoid force-push if possible

**Comment by MichaelChirico** [comment]
Thanks for the call-out, I especially regretted it here.

For context, this is what the Graphite tooling does -- I love the PR stacking but there are some other pain points. I'm still trying to learn all the nuances of a "mixed stack" -- my impression is their tooling is optimized for whole teams using the Graphite UI exclusively, but here we switch back & forth between Graphite+GitHub UIs / `gt`+`git` CLI commands.

**Comment by MichaelChirico** [comment]
FWIW it looks like Graphite has its own history logged, so the diff that got erased on git b/c of the force-push can be seen here:

https://app.graphite.dev/github/pr/Rdatatable/data.table/6106/Refactor-colClasses-handling-for-readability

(I compared `v6` vs `v9`)

**Comment by tdhock** [comment]
great, thanks

**Pull request merged**
