### PR TITLE
Frollmax2 rebase

### PR DESCRIPTION
**Pull request by MichaelChirico**
Hey @jangorecki I had a go at rebasing #5890 to `1-15-99`, PTAL and I'll force-push there if it looks like I succeeded.

### CODE REVIEW

**Comment by jangorecki** [comment]
Till late Feb/early March I may not have enough time to work on all PRs so I am considering it may be better to revert frollmax1, as it is possibly buggy, and come back to it later. Haven't look at the content of this PR yet but some commits seem to be missing authored/committed info.

**Comment by MichaelChirico** [comment]
> missing authored/committed info.

Yea, I saw that. Weird. I only did `git rebase 1-15-99` while checked out from this branch, then pushed, so not sure what happened. Alas.

> better to revert frollmax1

OK, happy to that then we just roll forward later.

**Comment by MichaelChirico** [comment]
Hmm GitHub UI looks to make `revert` complicated, I guess because it's merged to `1-15-99`. I will try reverting again once `1-15-99` is merged to `master`. For now the code is not touching master so it's no hurry anyway.

**Comment by jangorecki** [comment]
You can event force push to revert it invisibly

**Pull request closed without merging**
