### PR TITLE
Update datatable-intro.Rmd

### PR DESCRIPTION
**Pull request by gurbuxanink**
A powerful feature of data.table is the ability to store lists as elements (a facility not available in data.frame).  Here is a simple illustration of storing a fitted model as data.table element.

When statistical models are fit to different groups within a data.table, these models can be stored in a result data.table.  Now this resulting data.table can be used to access fitted models.

### CODE REVIEW

**Comment by tdeenes** [comment]
note that this is not exactly true, `data.frame`s __can__ hold list elements:
```
datfr <- data.frame(idx = 1:3)
datfr$lst <- lapply(datfr$idx, seq_len)
str(datfr)
# 'data.frame':	3 obs. of  2 variables:
#  $ idx: int  1 2 3
#  $ lst:List of 3
#   ..$ : int 1
#   ..$ : int  1 2
#   ..$ : int  1 2 3
```

Having said that, of course it is much more convenient to use `data.table`s for working with this kind of objects. E.g.:
```
lst <- lapply(1:3, seq_len)
## this works
data.table(idx = seq_along(lst), lst = lst)
## this fails
data.frame(idx = seq_along(lst), lst = lst)
```

**Comment by tdhock** [comment]
please clarify your proposed addition by mentioning that it is possible in frame but requires a bit more typing, since you have to wrap lists with `I()`
```r
> data.table(L=list(1:2))
        L
   <list>
1:    1,2
> data.frame(L=list(1:2))
  X1.2
1    1
2    2
> data.frame(L=I(list(1:2)))
     L
1 1, 2
```

**Comment by tdhock** [comment]
that looks better thanks

**Review by tdhock — APPROVED** [review]
great thanks!

**Pull request merged**
