### PR TITLE
Fixes for new rchk issues

### PR DESCRIPTION
**Pull request by MichaelChirico**
These just started appearing. Either a new LLVM version, or possibly an update to the docker image we're using that is pulling in a more recent version of rchk (rchk itself has no recent source code updates).

Report:

https://github.com/Rdatatable/data.table/actions/runs/11616716077/job/32350299506?pr=6595

All look related to `getAttrib()` usage, which may be newly marked as requiring `PROTECT()`.

### CODE REVIEW

**Comment by tdhock** [comment]
related, it looks like git2r is failing to install, because system libgit2 is no longer available, do we need to add an apt-get install or similar?
```

* installing *source* package ‘git2r’ ...
** package ‘git2r’ successfully unpacked and MD5 sums checked
** using staged installation
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking whether the libgit2 version will work in git2r... no

  -----------------------------------------------------------------------
configure: error: in '/tmp/Rtmp3q0xqQ/R.INSTALL164c558d2e9e/git2r':
configure: error: package dependency requirement 'libgit2 >= 1.0' could not be satisfied.

See 'config.log' for more details
   Configuration failed to find libgit2 library. Try installing:
     * brew: libgit2 (MacOS)
     * deb: libgit2-dev   (Debian, Ubuntu, etc)
     * rpm: libgit2-devel (Fedora, CentOS, RHEL)
   and try again.

   If the libgit2 library is installed on your system but the git2r
   configuration is unable to find it, you can specify the include and
   lib path to libgit2 with:

   given you downloaded a tar-gz archive:
   R CMD INSTALL git2r-.tar.gz --configure-vars='INCLUDE_DIR=/path/to/include LIB_DIR=/path/to/lib'

   or cloned the GitHub git2r repository into a directory:
   R CMD INSTALL git2r/ --configure-vars='INCLUDE_DIR=/path/to/include LIB_DIR=/path/to/lib'

   or download and install git2r in R using
   install.packages('git2r', type='source', configure.vars='LIB_DIR=-L/path/to/libs INCLUDE_DIR=-I/path/to/headers')

  -----------------------------------------------------------------------


ERROR: configuration failed for package ‘git2r’
```

**Comment by Anirban166** [comment]
> related, it looks like git2r is failing to install, because system libgit2 is no longer available, do we need to add an apt-get install or similar? @Rdatatable/performance-testers

Yup (here's [an example](https://github.com/Anirban166/Autocomment-atime-results/blob/eaeb67001d8238e2d148b4a1714fd7f67580fa31/action.yml#L40) from my action's code)

**Comment by tdhock** [comment]
@Anirban166 can you please submit another PR to fix?

**Comment by Anirban166** [comment]
> @Anirban166 can you please submit another PR to fix?

Certainly, but I'm a bit confused as to where you encountered that error (I checked the logs and didn't seem to find it; also [rchk](https://github.com/Rdatatable/data.table/blob/master/.github/workflows/rchk.yaml) doesn't seem to install `git2r` explicitly)

**Comment by tdhock** [comment]
it was from the atime (not rchk) CI job

**Comment by Anirban166** [comment]
Thanks, and I figured that a while ago so I've been testing some changes to my action in my fork (I'll create an issue on my repository since I think this is off-topic for this one), not sure what's up with the sudden `libgit2` incompatibility though

**Comment by Anirban166** [comment]
Thanks, and I figured that a while ago so I've been testing some changes to my action (I'll create an issue on that repository since I think this is off-topic for this one) in my `data.table` fork, not sure what's up with the sudden `libgit2` (version incompatibility?) issue though

**Comment by ben-schwen** [comment]
Interestingly we do not get these reported errors in the current subsequent runs without this PR.

**Comment by MichaelChirico** [comment]
Closing, it's easy enough to re-open if `rchk` starts complaining again.

**Pull request closed without merging**
