### PR TITLE
add link to base::strsplit in tstrsplit  documentation

### PR DESCRIPTION
**Pull request by jan-glx**

### CODE REVIEW

**Comment by jan-glx** [comment]
change is untested. sorry.

**Comment by MichaelChirico** [comment]
any reason to close? looks helpful to me

**Comment by MichaelChirico** [comment]
we don't test documentation so shouldn't affect anything

**Comment by jan-glx** [comment]
I meant that I did not clone&build to check if the syntax for links specifying packages really works like that. (close and reopen was bc. I realized that I did not read contributing.md)

**Comment by mattdowle** [comment]
Nice find.  Thanks!

**Pull request merged**
