### PR TITLE
fix CRAN noLD note

### PR DESCRIPTION
**Pull request by jangorecki**
should fix "noLD" note listed in Additional issues on CRAN check https://cran.r-project.org/web/checks/check_results_data.table.html

### CODE REVIEW

**Comment by QuLogic** [comment]
BTW, as a note, the system at #3492 has `sizeof(long double) == 8` and still passes this test, so it seems to only be a problem for systems without long double entirely.

**Comment by jangorecki** [comment]
Yes, there is noLD is an extra check on cran reported separately in additional issues section. And this PR was only meant to fix this.

**Comment by QuLogic** [comment]
Yes, but the check in this PR disabled the test for sizeof==8 as well, not just noLD.

**Comment by jangorecki** [comment]
This is not an issue, as per WRE those tests shouldn't be here in the first place. It make sense to keep them only to spot regression, so single common use case is enough.

**Comment by mattdowle** [comment]
@jangorecki  But something doesn't quite add up here.  @QuLogic has a point:  they have a machine on which .Machine$sizeof.longdouble is 8 and yet test 9999.024 passes for them.  That's strange isn't it?

**Comment by jangorecki** [comment]
> the system at #3492 (armv7hl) has sizeof(long double) == 8 and still passes this test

@QuLogic by "pass this test" you mean it is being evaluated? or simply does not raise error (thus is probably skipped).
Could you please check on latest devel? #3492 was about 1.12.2 and that test got changed later on.
Below code block so you don't need to run all tests:
```r
library(data.table)
test = data.table:::test
set.seed(108)
x = sample(c(rnorm(1e3, 1e6, 5e5), 5e9, 5e-9))
n = 15
ma = function(x, n, na.rm=FALSE) {
  ans = rep(NA_real_, nx<-length(x))
  for (i in n:nx) ans[i] = mean(x[(i-n+1):i], na.rm=na.rm)
  ans
}
fastma = function(x, n, na.rm) {
  if (!missing(na.rm)) stop("NAs are unsupported, wrongly propagated by cumsum")
  cs = cumsum(x)
  scs = shift(cs, n)
  scs[n] = 0
  as.double((cs-scs)/n)
}
ans1 = ma(x, n)
ans2 = fastma(x, n)
ans3 = frollmean(x, n)
ans4 = frollmean(x, n, algo="exact")
anserr = list(
  fastma = ans2-ans1,
  froll_fast = ans3-ans1,
  froll_exact = ans4-ans1
)
errs = sapply(lapply(anserr, abs), sum, na.rm=TRUE)
if (!(.Platform$OS.type=="windows" && getDTthreads()>1L)) { # windows 2+ threads rounding issue: #3346
  if (.Machine$sizeof.longdouble == 16L) test(9999.024, errs[["froll_exact"]]==0) # only where long double available, otherwise we get noLD CRAN note
  if (Sys.info()["machine"] == "x86_64") test(9999.025, errs[["froll_fast"]]>errs[["froll_exact"]]) # floating point arithmetic issue on various machines #3491
}
test(9999.026, errs[["fastma"]]>errs[["froll_exact"]])
test(9999.027, errs[["fastma"]]>errs[["froll_fast"]])
```

**Comment by mattdowle** [comment]
@jangorecki In #3492 they tested 1.12.2 and reported a total of 2 tests fail. Which means 9999.024 is running and passing.  This PR switches it off in 1.12.4 which they haven't tried yet.

**Comment by QuLogic** [comment]
Yes, that's correct; I've tested 1.12.2. I did not test 1.12.4 because that doesn't exist yet.

**Pull request merged**
