### PR TITLE
Do not include symbol on lhs of := in othervars

### LINKED ISSUE #2326: .SD mistakenly includes column being set when get() appears in j
When I use `:=` together with `.SD`, `.SDcols` and `get()`, for example, 

```r
dt[, z := ncol(.SD) + get("y"), .SDcols = "x"]
```

The first time is ok, but whenever `z` already exists, the code above will produce incorrect results since `.SD` includes both `x` and `z`, which should be `x` only, as restricted by `.SDcols`.

The following code is a minimal example and demonstrates the problem:

```r
library(data.table)

dt <- data.table(x = seq(1, 10), y = seq(10, 1))
dt[, z := ncol(.SD) + y, .SDcols = "x"]
dt
dt[, z := ncol(.SD) + get("y"), .SDcols = "x"]
dt

dt[, z := {
  str(.SD)
  ncol(.SD) + get("y")
}, .SDcols = "x"]

dt[, z := NULL]
dt[, z := {
  str(.SD)
  ncol(.SD) + get("y", inherits = FALSE)
}, .SDcols = "x"]
```

The output looks like 

```
> library(data.table)
> dt <- data.table(x = seq(1, 10), y = seq(10, 1))
> dt
     x  y
 1:  1 10
 2:  2  9
 3:  3  8
 4:  4  7
 5:  5  6
 6:  6  5
 7:  7  4
 8:  8  3
 9:  9  2
10: 10  1
> dt[, z := ncol(.SD) + y, .SDcols = "x"]
> dt
     x  y  z
 1:  1 10 11
 2:  2  9 10
 3:  3  8  9
 4:  4  7  8
 5:  5  6  7
 6:  6  5  6
 7:  7  4  5
 8:  8  3  4
 9:  9  2  3
10: 10  1  2
> dt[, z := ncol(.SD) + get("y"), .SDcols = "x"]
> dt
     x  y  z
 1:  1 10 12
 2:  2  9 11
 3:  3  8 10
 4:  4  7  9
 5:  5  6  8
 6:  6  5  7
 7:  7  4  6
 8:  8  3  5
 9:  9  2  4
10: 10  1  3
> dt[, z := {
+   str(.SD)
+   ncol(.SD) + get("y")
+ }, .SDcols = "x"]
Classes ‘data.table’ and 'data.frame':	10 obs. of  2 variables:
 $ x: int  1 2 3 4 5 6 7 8 9 10
 $ z: int  12 11 10 9 8 7 6 5 4 3
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, ".data.table.locked")= logi TRUE
> dt[, z := NULL]
> dt[, z := {
+   str(.SD)
+   ncol(.SD) + get("y", inherits = FALSE)
+ }, .SDcols = "x"]
Classes ‘data.table’ and 'data.frame':	10 obs. of  1 variable:
 $ x: int  1 2 3 4 5 6 7 8 9 10
 - attr(*, ".internal.selfref")=<externalptr> 
 - attr(*, ".data.table.locked")= logi TRUE
```

### PR DESCRIPTION
**Pull request by renkun-ken**
This is an attempt to fix #2326.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Hi Kun, thanks!

Please be sure to include tests and make sure the updated package compiles and that `test.data.table()` runs without error -- in particular I think it's likely there's a reason the LHS was included in `othervars`, which should be covered by another test, so this bug fix will have to allow that use case to continue to function.

See here:
https://github.com/Rdatatable/data.table/blob/master/Contributing.md

**Comment by mattdowle** [comment]
Hi Kun,
Thanks from me too.  In case you are on Ubuntu, I recently added my dev cycle in the cc.R file in the project root.  That's how to easily make changes and run all tests, at least how I do it.  Once that is passing you can do the longer R CMD build and R CMD check before pushing the pull request.  If you are on Mac or Windows then cc.R will likely need some tweaking.
Hope that helps,
Matt

**Comment by renkun-ken** [comment]
Thanks for reminding! I'm working on macOS at the moment (or may turn to Ubuntu if necessary) and will need a little while to get familiar with `data.table`'s testing and find out what breaks previous test cases.

**Comment by mattdowle** [comment]
Great PR!!  Thanks!

**Comment by MichaelChirico** [comment]
Nice @renkun-ken! The PR process can be a steep learning curve, glad you could navigate it :nerd_face:

**Pull request merged**
