### PR TITLE
[WIP] set operators RC1, closes #547

### LINKED ISSUE #547: [R-Forge #5248] implement "set" (as in setdiff, union etc..) operations for data.tables for convenience
Submitted by: Arun ; Assigned to: Nobody; [R-Forge link](https://r-forge.r-project.org/tracker/index.php?func=detail&aid=5248&group_id=240&atid=978)

`data.table` has already a very efficient way for getting `unique` and `duplicated`. It takes 0.5 seconds where base's unique takes 8 seconds for example - check [this benchmark on rpub](http://rpubs.com/asrinivasan/unique_dt_vs_df).

Similarly, why not use the internal engine to generate *set operations* on `data.table`?
- [ ] setdiff
- [ ] union
- [ ] intersect

Condition: Number of columns and column classes should match.

### PR DESCRIPTION
**Pull request by jangorecki**
Any feedback welcome, especially on documentation. I will try to add more tests and it should be ready to merge/rebase.

### CODE REVIEW

**Comment by jangorecki** [comment]
are you agree on default for new `all` argument in `fsetequal`?
presented together with base and dplyr defaults.
```r
setequal(c("a","a","b"), c("a","b"))
#[1] TRUE
setequal(dplyr::data_frame(V1 = c("a","a","b")), dplyr::data_frame(V1 = c("a","b")))
#FALSE: Different number of rows
as.logical(.Last.value)
#[1] FALSE
fsetequal(data.table(c("a","a","b")), data.table(c("a","b")), all=TRUE)
#[1] FALSE
fsetequal(data.table(c("a","a","b")), data.table(c("a","b")))
#[1] TRUE
```

**Comment by arunsrinivasan** [comment]
The default usage would be, I guess, to check for exactness (correct me if you think otherwise).. If so, that'd be confusing. I'd skip `all` for `setequal`.

**Comment by arunsrinivasan** [comment]
We can revisit later if there's a known usage of `all` for `setequal`..

**Comment by jangorecki** [comment]
adding benchmarks on the latest commit: https://gist.github.com/jangorecki/6f0358a8c1142ad606f7

**Pull request merged**
