### PR TITLE
Add a simple dockerfile for extending basic CI image to do dev stuff (first: git)

### PR DESCRIPTION
**Pull request by MichaelChirico**
(might need to iterate few times, sorry for the PR noise)

### CODE REVIEW

**Comment by jangorecki** [comment]
In the next iteration put directory to .Rbuildignore

**Comment by MichaelChirico** [comment]
Did 4fcf81c1e4ca002985d2d9862a10c699255bf7db not work?

**Comment by jangorecki** [comment]
Probably did. My comment was based on a yesterdays state. Sorry

**Comment by jangorecki** [comment]
@MichaelChirico any idea if path `./.devcontainer` is configurable in some way? we do have `./.dev` directory where such directory would fit very well. To declutter directory.

**Comment by jangorecki** [comment]
? @MichaelChirico

**Comment by MichaelChirico** [comment]
Ah thanks. I lost track of where you posted that Q.

Not according to the official spec:

https://containers.dev/implementors/spec/

**Comment by MichaelChirico** [comment]
I also see this https://github.com/devcontainers/spec/issues/159

**Comment by jangorecki** [comment]
Him, then looks we are stuck with two different dirs in a root dir related exclusively to .github.

**Pull request merged**
