### PR TITLE
brazil and fr logos

### PR DESCRIPTION
**Pull request by tdhock**
related to #6221 and #6206 
I created logos for translation teams (which are displayed, for example, on https://github.com/orgs/Rdatatable/teams/french) by putting the DT hex sticker on top of flags.
This PR adds the source SVG files along with the PNG exports to the .graphics directory.

### CODE REVIEW

**Comment by ChristianWia** [comment]
how does the logo identify that translators are concerned ? it rather identifies  the french version of data.table

**Comment by tdhock** [comment]
Hi Christian, thanks for your feedback.
My intent was for the logo to identify the target translation language. 
I am not sure how to visually identify that translators are concerned. Can you clarify what you had in mind?
If you have any ideas to improve, please share and/or edit the files in this PR/branch directly.

**Comment by phgrosjean** [comment]
Thank you @tdhock. This looks nice.

**Comment by ChristianWia** [comment]
It came from "logos for translation teams ". In fact the logo is good for any one and as I said identifies the french version of data.table whatever a french data.table item is used (translation team, article, topic ...and vignette also.) . This way i understand better.. It's ok.

**Comment by leofontenelle** [comment]
As long as the flags are used internally (and new translators are OK with them) I see no problem. More generally, though, I'd like to remember there's [criticism of flags as symbols for spoken languages](https://en.wikipedia.org/wiki/Flag_icons_for_languages#Criticism).

**Comment by MichaelChirico** [comment]
Can you elaborate the context in which these will be used?

BTW, the non-transparent background is highlighting that the underlying logo has some weird edge behavior that looks a bit messy. Is it possible to address this?

**Comment by tdhock** [comment]
I intended these logos to be displayed on team pages such as https://github.com/orgs/Rdatatable/teams/french
I'm not sure what you mean by the weird edge behavior, can you please clarify? For me the edges of the hexagon look black.

**Comment by MichaelChirico** [comment]
> I intended these logos to be displayed on team pages such as https://github.com/orgs/Rdatatable/teams/french

Sounds great

> I'm not sure what you mean by the weird edge behavior, can you please clarify?

image

Yes, I mean  these transitional parts along the non-linear border of the seal

**Comment by tdhock** [comment]
ok thanks for clarifying. those white edges along the whiskers and body of the seal are indeed present in the original logo. so we should try to fix that here before merging.

**Comment by MichaelChirico** [comment]
> we should try to fix that here before merging.

FWIW, I see the logos already added to the teams page & the compression there hides these issues. So we _could_ earmark it for a future improvement. Either way.

**Comment by tdhock** [comment]
> As long as the flags are used internally (and new translators are OK with them) I see no problem. More generally, though, I'd like to remember there's [criticism of flags as symbols for spoken languages](https://en.wikipedia.org/wiki/Flag_icons_for_languages#Criticism).

That makes sense. If anyone wants to propose an alternative to flags, that would be great.
Closing for now because I mainly just wanted to upload these somewhere, so this branch is fine (I don't really care about this making it into master).

**Comment by jmrung** [comment]
Made some new versions of the translation team logos that incorporate the updated data.table logo (see #6425). I also included .png exports that show versions where the flags are completely within the hex; these are included in the svgs, with the corresponding layer group currently set to hidden.

I'm not sure the best way to provide the files since this is closed. Let me know if you'd like them another way, @tdhock 

datatable_Brazilfull
rdatatable_brazil
rdatatable_brazil
rdatatable_fr
rdatatable_fr
rdatatable_FRfull

**Comment by tdhock** [comment]
Thanks, those look great!
I invited you as a project member, which gives you permission to create new branches under Rdatatable.
Please create a new branch/PR and add/push your new artwork.

**Comment by tdhock** [comment]
we have a few other translation teams now (and Arabic coming soon probably) so if you have time please create logos for the others as well https://github.com/orgs/Rdatatable/teams/translators/teams
and when you file the PR please the software you used (either in a PR comment, or in a README.md file in the .graphics directory)

**Comment by rikivillalba** [comment]
Curiously, there exists a "panhispanic" flag, but it is almost entirely unknown.
https://en.wikipedia.org/wiki/Flag_of_the_Hispanic_People
Sites that use flags to choose language tend to use the flag of Spain to represent (castilian) spanish.

**Comment by tdhock** [comment]
nice find!
For the French-speaking people, there is la Francophonie, which also has a flag/logo that I was not aware of! 
https://en.wikipedia.org/wiki/Organisation_internationale_de_la_Francophonie

**Comment by tdhock** [comment]
> I'd like to remember there's [criticism of flags as symbols for spoken languages](https://en.wikipedia.org/wiki/Flag_icons_for_languages#Criticism).

There is "an [international organization](https://en.wikipedia.org/wiki/International_organization) and political association of [Lusophone](https://en.wikipedia.org/wiki/Lusophone) nations across five [continents](https://en.wikipedia.org/wiki/Continents), where [Portuguese](https://en.wikipedia.org/wiki/Portuguese_language) is an official language" https://en.wikipedia.org/wiki/Community_of_Portuguese_Language_Countries @leofontenelle do you think it would be more appropriate to use that logo, instead of the brazil flag?

**Comment by leofontenelle** [comment]
Not so much in our case, because pt_BR does focus on the Brazilian way of speaking Portuguese. If we had the same translation team serving equally all countries, this flag would serve us better than Portugal's one. BTW nice idea, I had seen this flag before but hadn't thought of it to symbolize the Portuguese language.

**Comment by jmrung** [comment]
Great discussions, and thanks for adding me as a member @tdhock! Happy to create a new branch/PR, but I'm going to pause until hearing back on an alternative I'd like to suggest given the issues with the use of flags.

It looks like there is a system of language codes, which there are a few versions of (e.g., two and three letter, [see list here](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes)). There's also versions with country codes added that could be used as needed ([see list here for examples](https://www.andiamo.co.uk/resources/iso-language-codes/)). Perhaps the two letter codes could be used in the following way, instead:

rdatatable_FR_CD

This would have the benefit of identifying the language in a standard way with the first two letters, and then any important distinctions could be added as indicated in the second list I linked to (e.g., PT-BR if needed for the Brazilian way of speaking Portuguese). 

Thoughts?

**Comment by tdhock** [comment]
that is fine, great idea!

**Pull request closed without merging**
