### PR TITLE
snprintf test9

### LINKED ISSUE #4545: dt_win_snprintf test 9 failed: snprintf:
Follow-up to #4531 

Seeing this in dev now on my Mac:

```
.Call(data.table:::Ctest_dt_win_snprintf)
Error: dt_win_snprintf test 9 failed: snprintf:
```

So test 2141 fails.

Should we be just skipping these tests on Unix?

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #4545

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Output for me:

```
Running test id 2141      Test 2141 produced 1 errors but expected 0
Expected: 
Observed: dt_win_snprintf test 9 failed: snpf8 sec
```

My `~/.R/Makevars`:

```
# The following is added per data.table/wiki/Installation
LLVM_LOC = /usr/local/opt/llvm
CC=$(LLVM_LOC)/bin/clang -fopenmp
CXX=$(LLVM_LOC)/bin/clang++ -fopenmp
CFLAGS=-g -O3 -Wall -pedantic -std=gnu99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L$(LLVM_LOC)/lib -Wl,-rpath,$(LLVM_LOC)/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I$(LLVM_LOC)/include
```

**Comment by MichaelChirico** [comment]
Changed `CFLAGS` to be `-std=c99` and the output looks the same:

```
Running test id 2141      Test 2141 produced 1 errors but expected 0
Expected: 
Observed: dt_win_snprintf test 9 failed: snpf8 sec
```

**Comment by MichaelChirico** [comment]
One last test using `gcc`:

```
Observed: dt_win_snprintf test 9 failed: snpf8 sec
Running test id 2147.2      
```

Makevars:

```
GCC_LOC=/usr/local/gfortran
CC=$(GCC_LOC)/bin/gcc -fopenmp
CXX=$(GCC_LOC)/bin/g++ -fopenmp
CFLAGS=-g -O3 -Wall -pedantic -std=c99 -mtune=native -pipe
CXXFLAGS=-g -O3 -Wall -pedantic -std=c++11 -mtune=native -pipe
LDFLAGS=-L/usr/local/opt/gettext/lib -L$(GCC_LOC)/lib -Wl,-rpath,$(GCC_LOC)/lib
CPPFLAGS=-I/usr/local/opt/gettext/include -I$(GCC_LOC)/include
```

And a line from compilation:

```
/usr/local/gfortran/bin/gcc -fopenmp -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I/usr/local/opt/gettext/include -I/usr/local/gfortran/include   -fPIC  -g -O3 -Wall -pedantic -std=c99 -mtune=native -pipe -c wrappers.c -o wrappers.o
```

**Comment by mattdowle** [comment]
Great, thanks. That wasn't what I expected: error 8 instead of 9. Ok so I shortened the error output so we can see the two numbers in the output. Please try again.

**Comment by MichaelChirico** [comment]
updated output:

```
Running test id 2141      Test 2141 produced 1 errors but expected 0
Expected: 
Observed: dt_win_snprintf test 9 failed: 8 57 23 s
```

PS would you mind quickly merging #4473? since whenever I run `test.data.table()` now I get 6 failures that would be fixed by that, those 6 are a bit distracting

**Comment by mattdowle** [comment]
Great, thanks. Pretty sure the last commit will fix it. Surprised that test passed at all before. I'll continue to merge as that's almost surely it; the 57 (instead of 23) in the output is consistent with a non-reset ap via garbage pointer with random integers being placed there resulting in a wider output.
If not, please reopen.

**Comment by MichaelChirico** [comment]
Just realized I never sent the result yesterday, e2cb3c6 indeed fixed it

```
All 9913 tests in tests/tests.Rraw completed ok in 00:01:00 elapsed (00:01:36 cpu)
```

**Pull request merged**
