### PR TITLE
Closes #1177: print.data.table now has quote option mirroring that of print.data.frame

### LINKED ISSUE #1177: `print` not obeying `quote=T` argument
I'm testing output after trimming some whitespace from some character fields to make sure everything looks right; this exercise of course requires being able to detect whether whitespace still exists.

The default print method for `data.table`s does not allow this:

    dt<-data.table(str=c("   yo  "))
    print(dt,quote=T)
          str
    1:    yo 

But this option is helpful for `print.data.frame`:

    print.data.frame(dt,quote=T)
           str
    1 "   yo "

The problem is `print.data.frame` immediately converts the object to a `matrix` before passing it to `print.default` -> `.Internal(print.default(...))`, which has no immediate port to `data.table`s due to the middle clipping.

### PR DESCRIPTION
**Pull request by MichaelChirico**
It seems this fix was as easy as this. Let me know if you'd like to add tests.

### CODE REVIEW

**Comment by jangorecki** [comment]
Unit tests would be nice for both cases of `quote` arg. I believe the test will expose the current issue in your code ;) Easy testing print can be done by `capture.output`, there are already tests which utilize that.

**Comment by MichaelChirico** [comment]
@jangorecki i did run some basic checks & it seemed fine; you're thinking of the extraneous quotes on the dotted-out (`---`) lines?

**Comment by jangorecki** [comment]
Yes, it looks OK. I edited my comment already, my initial comment was due looking at the left side of *compare* screen - so the previous version. Anyway unit tests are always good.

**Comment by MichaelChirico** [comment]
@jangorecki  tests added, let me know if you think something more robust is called for

**Pull request merged**
