### PR TITLE
isolate tests.Rraw from variables created by user in .GlobalEnv

### LINKED ISSUE #3705: tests fail if z in .GlobalEnv
```
library(data.table)
z = 4
test.data.table()
```

```
Error in test.data.table() : 
  3 errors out of 9118 in 00:01:00 elapsed (00:02:40 cpu) on Thu Jul 11 08:46:42 2019. [endian==little, sizeof(long double)==16, sizeof(pointer)==8, TZ=Asia/Singapore, locale='LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=C', l10n_info()='MBCS=TRUE; UTF-8=TRUE; Latin-1=FALSE', getDTthreads()='omp_get_num_procs()==8; R_DATATABLE_NUM_PROCS_PERCENT=="" (default 50); R_DATATABLE_NUM_THREADS==""; omp_get_thread_limit()==2147483647; omp_get_max_threads()==8; OMP_THREAD_LIMIT==""; OMP_NUM_THREADS==""; data.table is using 4 threads. This is set on startup, and by setDTthreads(). See ?setDTthreads.; RestoreAfterFork==true']. Search tests/tests.Rraw for test numbers: 1894.09, 1894.13, 1894.14
```

```
if (exists("z")) rm(z)
test(1894.09, DT[, sum(z)*..z], error="Variable 'z' is not found in calling scope. Looking in calling scope because this symbol was prefixed with .. in the j= parameter.")
z = 3L
test(1894.10, DT[, sum(z)*..z], 72L)
setnames(DT, "z", "..z")
test(1894.11, DT[, sum(y)*..z], INT(105,120,135))
rm(z)
test(1894.12, DT[, sum(y)*..z], INT(105,120,135))
setnames(DT, "..z", "z")
test(1894.13, DT[, sum(y)*..z], error="Variable 'z' is not found in calling scope")
..z = 4L
test(1894.14, DT[, sum(y)*..z], 60L)  # 'manual' prefix (we have recommended in the past) still works, for now.
```

There's `if (exists('z')) rm(z)` but that didn't work?

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #3705

Could change `z` to be an unusual name such as `foo6937265` and skip the test in the unusual case that even that was in .GlobalEnv.  However, trying to tackle the root cause by changing the parent of the env that tests run inside, so we never have this issue again.

First commit set parent to `parent.env(.GlobalEnv)` which is `search()[2]`. This worked in that test 1894 no longer sees the `z` in `.GlobalEnv`.  However, then other tests which load `bit64` fail because when they are loaded at the top of tests.Rraw they become the new position 2 and functions like `as.integer64()` are not found because the parent of the env is now position 3 (the old position 2).

Hence tests.Rraw now attaches suggests at the end of `search()`.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
pretty cool & straightforward if it works. otherwise, what about something like

(1) copy .GlobalEnv to tmpEnv
(2) run tests
(3) on.exit, copy tmpEnv to .GlobalEnv

risk being user has large objects which are expensive to copy...

**Comment by mattdowle** [comment]
I guess there's a missing step (1.5) which removes everything in .GlobalEnv. If so, that not allowed by CRAN policy; e.g. what if tests fail or the on.exit somehow doesn't run, or the on.exit does run but only gets through half the restore.

**Comment by MichaelChirico** [comment]
mitigated by iterating the overwrite but fair, it's not a great solution if we can avoid it.

**Comment by mattdowle** [comment]
I checked R 3.1.0's `library()` function has all the arguments this PR uses: `character.only`, `logical.return`, `quietly`, `warn.conflicts` and `pos`.

**Pull request merged**
