### PR TITLE
Link fix in vignettes for CRAN checks

### LINKED ISSUE #6166: Release data.table version 1.16.0
We are nearing our planned 6-month cadence for a non-patch release.

Filing this issue to track progress and as a call to flag issues for inclusion in / exclusion from the milestone:

https://github.com/Rdatatable/data.table/milestone/30

Let's see what we can finish by the end of June. Lots of goodies in the release already! Thanks for everyone's work :)

TODO

- [x] include patch release NEWS to master for 1.15.{2,4}
- [x] final pass over NEWS file for readability

### PR DESCRIPTION
**Pull request by TysonStanley**
Closes #6166 with minor changes to vignettes

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I see 1.16.0 on CRAN, is this going to be part of a patch?

**Comment by TysonStanley** [comment]
No, this was part of the release to CRAN to pass the checks.

**Comment by MichaelChirico** [comment]
Oh, got it. 8f39d2ce06fce5407b30b86b43f20ec2cdaf41f9 didn't make it in, right? Should we revert that so it's not included in the 1.16.0 tag?

**Comment by TysonStanley** [comment]
No, that one did not make it. Might make sense to revert for that reason and then recommit in 1.16.99

**Comment by TysonStanley** [comment]
Note that the tag is now live on GitHub based on the submitted version. Outside of version bumps and compression, any other changes are now on master (after you merged this). Other version bumps will need to be done to 1.16.99.

**Pull request merged**
