### PR TITLE
Fixing bug in 'on' with complex variable names

### LINKED ISSUE #2931: Strange behavior when subsetting with column names quoted with backticks in I of data.table
Subsetting with complex column names quoted with backticks will throw errors. See the following reproducible example:
```
library(data.table)

DT <- data.table(id = letters[1:3], `counts(a>=0)` = 1:3)

DT[`counts(a>=0)` == 2] 
#> Error in `[.data.table`(DT, `counts(a>=0)` == 2): Column(s) [counts(a] not found in x
```
This has been posted on Stackoverflow [here](https://stackoverflow.com/questions/50810759/strange-behavior-when-subsetting-with-column-names-quoted-with-backticks-in-i-of). This seems to be an issue exists in v1.11.+ (as found by [David Arenburg](https://stackoverflow.com/users/3001626/david-arenburg) and [PKumar](https://stackoverflow.com/users/1894388/pkumar)) but not previous release. I tried the developmental version and got the same error. David Arenburg has investigated this issue and found it might be caused by [`.prepareFastSubset`](https://github.com/Rdatatable/data.table/blob/master/R/data.table.R#L418) (see the comments in the linked SO post for details), which I think would be very helpful to fix this issue.

Some workarounds like `` DT[as.numeric(`counts(a>=0)`) == 2] `` and `` DT[(`counts(a>=0)`) == 2] ``  by [Aurelien callens](https://stackoverflow.com/users/9901566/aurelien-callens) and [Marius](https://stackoverflow.com/users/1222578/marius) work fine.

Here is the session info:

```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.4 LTS

Matrix products: default
BLAS: /usr/lib/atlas-base/atlas/libblas.so.3.0
LAPACK: /usr/lib/atlas-base/atlas/liblapack.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.11.5

loaded via a namespace (and not attached):
[1] compiler_3.4.4 tools_3.4.4    yaml_2.1.17
```

### LINKED ISSUE #3092: 'on' clause fails on white spaces around operators and on operators in variable names
The issue originally popped up her : #2931.
There are two issues from my perspective with 'on'.

**First:**
White spaces around operators make it fail: 
```
DT <- data.table(a = 1:3, b=1:3)
i <- data.table(ai = 1:3, bi = 1:3)
DT[i, on = "a >= ai"]
## throws error
```
***Second:***
Column names including operators make it fail
``` 
DT <- data.table(`a>=` = 1:3, b = 1:3)
i   <- data.table(ai = 1:3, bi = 1:3)
DT[i, on = "`a>=`==ai"]
## throws error

### PR DESCRIPTION
**Pull request by MarkusBonsch**
Closes #3092 
Closes #2931

**Changes**
The logic, how the 'on' string gets parsed and variable names + operators are extracted has been rewritten in order to:
* fix bug where complex variable names with operators in the on clause caused an error, e.g. `colA>=1`
* allow white spaces around the operators in an on clause
Many thanks to @telenz for figuring out the algorithm.

**Tests**
* No existing tests changed.
* 8 new tests added

I am assuming that the documented standard behaviour of 'on' is thoroughly tested already. Therefore, new tests only comprise situations with complex variable names including operators like `colA>=1` and 'on' clauses with white spaces around the operator.

**Performance**
No significant additional overhead. Tests in `tests.Rraw` run as fast as before. The following example with a rather complex 'on' clause shows no speed impact of back-tick 'ed variable names:
```
library(data.table)
library(microbenchmark)
DT <- data.table(`a1>=` = 1:3, `<=b` = 1:3, `==c` = 1:3, `d==` = 1:3)
DT2 <- data.table(a = 1:3, b = 1:3, c = 1:3, d = 1:3)
i  <- data.table(`a1>=i` = 1:3, `<=bi` = 1:3, `==ci` = 1:3, `d==i` = 1:3)
i2  <- data.table(ai = 1:3, bi = 1:3, ci = 1:3, di = 1:3)
DT[i, on = c("`a1>=` == `a1>=i`", "`<=b` == `<=bi`", "`==c` == `==ci`", "`d==` == `d==i`")]
test <- microbenchmark(backTick = DT[i, on = c("`a1>=` == `a1>=i`", "`<=b` == `<=bi`", "`==c` == `==ci`", "`d==` == `d==i`")], 
                       noBackTick = DT2[i2, on = c("a==ai", "b==bi", "c==ci", "d==di")],
                       times = 100)
# Unit: milliseconds
#        expr        min         lq             mean       median           uq      max            neval
#      backTick 1.698332 1.776262 1.964937 1.840638 1.911018 5.127662   100
#  noBackTick 1.641280 1.728642 1.881203 1.798994 1.873094 5.633216   100

### CODE REVIEW

**Comment by MarkusBonsch** [comment]
I tend to strongly agree with you @jangorecki  :). Therefore, I have factored it out in the latest commit.
Thanks for the review and the suggestion!

**Comment by MarkusBonsch** [comment]
Thanks @mattdowle for the review. I have adapted the tests so that all stops and branches are hit. Still, diff coverage is only 98.3 %. Looking into it suggests, that a curly bracket after an `if` statement is missed even though the `if` statement is hit in general. This seems to be a bug in codecov, IMHO. So I think, we have full coverage here.

**Comment by mattdowle** [comment]
I filed the covr issue here : https://github.com/r-lib/covr/issues/339

**Comment by jangorecki** [comment]
we need to replace `trimws` as R 3.1 raises
```
Error in .parse_on(substitute(on), isnull_inames) : 
  could not find function "trimws"
Calls: all.equal ... all.equal.data.table -> [ -> [.data.table -> .parse_on
```

**Comment by MichaelChirico** [comment]
trimws is a very simple helper function... we should add it to utils `if` session R version < 3.2

**Comment by mattdowle** [comment]
To link it for completeness, `trimws` was backported here:  https://github.com/Rdatatable/data.table/pull/3114

**Pull request merged**
