### PR TITLE
Add patch release NEWS to master

### PR DESCRIPTION
**Pull request by MichaelChirico**

### CODE REVIEW

**Comment by tdhock** [comment]
great, why wasn't that there before?

**Comment by MichaelChirico** [comment]
> great, why wasn't that there before?

an oversight of the "new" approach to versioning that's just building patches off the previous even version. so those items only wind up in patch branches. See #5989.

**Comment by TysonStanley** [comment]
Sounds like a step I need to include in the patch release? Can add to the release docs.

**Comment by MichaelChirico** [comment]
@TysonStanley PTAL at #5989! I had a pass at doing just that. appreciate your extra eyes + further refinement.

**Comment by TysonStanley** [comment]
> @TysonStanley PTAL at #5989! I had a pass at doing just that. appreciate your extra eyes + further refinement.

Sorry, missed that notification. Will review now.

**Pull request merged**
