### PR TITLE
Fix divergence between CRAN version and master

### LINKED ISSUE #6587: Master diverges from patch 1.16.2
Currently, we have commits in our last CRAN version which are not part of current master, e.g. [9de2567](https://github.com/Rdatatable/data.table/commit/9de25675aa9f6efe982f4faff0ceb6ca55563563)

### PR DESCRIPTION
**Pull request by ben-schwen**
Closes #6587

This PR merge the `patch-1.16.2` branch into curent `master`. After resolving the conflicts it shows that we indeed are only missing #6563

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I believe I saw the 1.16.2 NEWS missing from master too, would you mind merging that in this PR as well?

**Comment by ben-schwen** [comment]
> I believe I saw the 1.16.2 NEWS missing from master too, would you mind merging that in this PR as well?

Done, unfortunately I had to renumber the NEWS items manually.

**Comment by TysonStanley** [comment]
Sorry about that, oversight on my part. Can PR the NEWS as soon as it's accepted to avoid having to renumber too much. Is there a good way to get the rest of the stuff in there or just a larger PR like this one with the relevant commits to the patch?

**Comment by MichaelChirico** [comment]
> Is there a good way to get the rest of the stuff in there or just a larger PR like this one with the relevant commits to the patch?

I think this is new territory for all the maintainers, open to ideas. It definitely feels a bit clunky.

**Pull request merged**
