### PR TITLE
updating class argument to print.data.table, #1523

### PR DESCRIPTION
**Pull request by MichaelChirico**
Should fix everything.

@arunsrinivasan two tangentially related things:

 1. I found a bunch of tests which seem like they're up for the chopping block (all the ones with `test(off-` -- there's a message saying those tests should be deleted after Sep 2015. The old `bywithoutby` tests.

 2. Tests 1378.2 & 1378.3 consistently produce errors for me. At a glance, it seems like the tests are only meant to run on a Windows machine (I'm on Linux), should there be an `if` clause there?

### CODE REVIEW

**Comment by MichaelChirico** [comment]
@arunsrinivasan not sure what to do about the `.Rout` errors.

Test 1293 needs to be changed, I guess? The table is now wider than 80 characters, so it will be force-wrapped.

**Comment by jangorecki** [comment]
my suggestion would be to isolate moving of print.data.table to own R files as a separate commit, so diff will be meaningful when looking what was changed in the commit.

**Comment by MichaelChirico** [comment]
@jangorecki I agree in principle, but here the changes to `print.data.table` itself were trivial. [Deleted: 158-159](https://github.com/Rdatatable/data.table/pull/1586/files#diff-650e4a11ed4384f8e560a6ebfff4ff53L157), [Added: 66-67](https://github.com/Rdatatable/data.table/pull/1586/files#diff-b0b075f88b03787a833ba65099018ebdR66). All the problems are coming from having changed `onLoad.R` so that the class name prints by default, which has cascaded up through all the other tests... if you still prefer separate commits let me know and I'll redact.

**Comment by arunsrinivasan** [comment]
+1 @jangorecki

**Comment by MichaelChirico** [comment]
Done.

**Comment by jangorecki** [comment]
OK, thanks.
I understand it is small change but for example making a git diff patch to revert a single commit would be problematic in that case. Additionally if extracting statistics from git it is easier to isolate move commits from real change commits. If change A is not related to change B, they shouldn't be in single commit.

**Comment by MichaelChirico** [comment]
I'm with you -- my thinking was more that I prefer to save you guys time (one PR instead of 2, especially given that the second consists solely of X-pasting code to a new file). But you're absolutely right that it's more savvy from a package development / transparency perspective, which is of course more important than expediency.

**Comment by arunsrinivasan** [comment]
Closing this following Jan's point.

**Comment by MichaelChirico** [comment]
@arunsrinivasan `class` still prints as:

```
col
<type>
data
```

Are you fine with that now, or do you still want

```
<type>
col
data
```

**Pull request closed without merging**
