### PR TITLE
allow rbind for integer64 and character/complex/vector

### LINKED ISSUE #5504: rbindlist internal error when binding integer64 + character columns
```r
rbindlist(list(
  data.table(bit64::as.integer64(1)),
  data.table("1")
))
Error in rbindlist(list(data.table(bit64::as.integer64(1)), data.table("1"))) : 
  Internal error: column 1 of result is determined to be integer64 but maxType=='character' != REALSXP
```

### PR DESCRIPTION
**Pull request by ben-schwen**
Closes #5504

### CODE REVIEW

**Comment by MichaelChirico** [comment]
I thought this might be covered by #5446, but I confirm the issue in #5504 is still present on `master`.

Would you mind updating this PR?

**Comment by ben-schwen** [comment]
> Would you mind updating this PR?

Will do at the weekend

**Comment by MichaelChirico** [comment]
Funny it took till now to find the issue with test 2265 re-attaching {bit64} incorrectly. But I did see that same error in a different context & shrugged it off. Now understood(ish) and fixed.

**Review by MichaelChirico — APPROVED** [review]
I wonder why always using `coerceAs()` doesn't "just work" but switching broke a lot of tests; left for future exercise :)

**Pull request merged**
