### PR TITLE
handles integer vector stored as matrix in i, closes #826

### LINKED ISSUE #826: [Request] subset DT on integer vector stored as matrix the same way as data.frame
Kind of minor FR.
Quite common use case when using `caret` package for machine learning.
Bellow command (random partition indices for training and testing machine learning model):
`idx_training <- createDataPartition(dt$response, p = 0.75, list = FALSE)`
will produce integer vector but with length of second dimension equal to 1.
```
> str(idx_training)
 int [1:2188, 1] 6 12 15 22 25 33 45 46 50 62 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : chr "Resample1"
```
when subsetting this on data.frame as follows:
`as.data.frame(dt)[idx_training,]`
it will works just fine.

But when trying to subset on data.table:
```
dt[idx_training]
dt[idx_training,] # even tried this way on data.table
```
it will throw an error like that:
```
Error in `[.data.table`(dt, idx_training) : 
  i is invalid type (matrix). Perhaps in future a 2 column matrix could return a list of elements of DT (in the spirit of A[B] in FAQ 2.14). Please let datatable-help know if you'd like this, or add your comments to FR #1611.
```

So the finally the FR is:
 - support for subset integer vector stored as matrix when `dim(int_vector)[2]==1`
 - behave the same as data.frame - in terms of subsetting in such case

I think it is not a big deal and better integration with data.frame is always good.

Of course it currently can be done just by `dt[idx_training[,1]]`, that's why it's minor.

### PR DESCRIPTION
**Pull request by jangorecki**
Simple and I believe completed solution to close #826

### CODE REVIEW

**Comment by arunsrinivasan** [comment]
Could you please also add an item to NEWS, and add about this feature in the `i` argument of `?data.table`? Thanks.

**Comment by jangorecki** [comment]
The `?data.table` is already covered by sentence:
> Integer and logical vectors work the same way they do in [.data.frame.

So no update required I believe. It is a special case of integer vector with second dimension artificially created. Description of it can be more confusing. I will update NEWS and put that to into bugfixes as it is bugfix comparing to data.frame behaviour.

**Comment by arunsrinivasan** [comment]
I'm not following. Where does it mention `1-col matrix`?

**Comment by jangorecki** [comment]
It mentions the same way as data.frame which already handles such cases. If you believe such case should be explicitly mentioned I can add it if you fell it is really needed, I doubt if people stores integer vectors as such matrix intentionally.

**Comment by jangorecki** [comment]
It seems to be right in time, see http://stackoverflow.com/questions/32509803/creating-a-data-partition-using-caret-and-data-table :)

**Comment by jangorecki** [comment]
Looks like PR is right in time, see http://stackoverflow.com/questions/32509803/creating-a-data-partition-using-caret-and-data-table

**Comment by arunsrinivasan** [comment]
@jangorecki will take a look asap. You might want to resolve the conflicts in the meanwhile?

**Comment by jangorecki** [comment]
@arunsrinivasan will try today/tomorrow

**Comment by arunsrinivasan** [comment]
sure.

**Comment by jangorecki** [comment]
Finally learned some *rebase*  :) once travis pass I think it is ready to merge.

**Comment by cmdcolin** [comment]
I was getting an error that referred here and also looked at https://github.com/Rdatatable/data.table/issues/826

With sample code

```
x=data.table(a=1:10,b=2:11)
subset(x,(x[,1]>5))
```

The workaround to do subset(x,(x[,1]>5)[,1]) does work but curious if it is necessary? using data.table 1.10.4

**Comment by cmdcolin** [comment]
Woops meant to post #657

**Pull request merged**
