### PR TITLE
 New alias `setcolnames()` for `setnames()`

### LINKED ISSUE #5640: Add `setcolnames()` as an alias for `setnames()`
### Rationale:

`colnames()` on a data.frame/.table returns the same thing as `names()`, and IMO is clearer style. `setcolnames()` would follow this convention, would parallel `setcolorder()`, and AFAICT would not conflict with function names from any other common packages. Of course you'd want to leave `setnames()` as a synonym for backwards-compatibility (and for fewer keystrokes for those who disagree with me on style).

### PR DESCRIPTION
**Pull request by Nj221102**
This PR Closes #5640 , adding  alias `setcolnames()` for `setnames()` by making such changes :- 

1. adding the alias `setcolnames()`  in function `setnames()` which is present in  R/data.table.R
2. updating the documentation and  News.md about the changes.
3. exporting the `setcolnames()` from the NAMESPACE.
4. adding test for newly added feature.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
@jangorecki @tdhock please just review with :-1: if you'd rather not add this alias. I can handle the rest of the review.

**Comment by MichaelChirico** [comment]
Thanks @tdhock! Please feel free to close #5640

**Comment by MichaelChirico** [comment]
@Nj221102 have you browsed [`label:beginner-task`](https://github.com/Rdatatable/data.table/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner-task)? I know you were asking about suggestions where to contribute.

**Comment by Nj221102** [comment]
> @Nj221102 have you browsed [`label:beginner-task`](https://github.com/Rdatatable/data.table/issues?q=is%3Aopen+is%3Aissue+label%3Abeginner-task)? I know you were asking about suggestions where to contribute.

Yeah will look into them , thanks :)

**Pull request closed without merging**
