### PR TITLE
Retrospective license change permission

### PR DESCRIPTION
**Pull request by mattdowle**
Dear @dselivanov, @chenghlee, @cooldome, and @blasern,

You are receiving this because you have contributed code to the data.table project before Nov 2017 but were not consulted in the license change PR #2456. The reason you were missed is shown below. A recent discussion, thanks to @dselivanov, instigated a review: see the bottom of PR #1236. The result of this review is that your 4 names are the ones we need to retrospectively ask your permission for the license change, and also add your names to list of contributors in DESCRIPTION which is displayed on CRAN.

Who | PR | Why |
-- | -- | -- |
@dselivanov | #1236 | Missing from GitHub contributors page due to invalid format email address
@cooldome | #1434 | Missing from GitHub contributors page due to invalid format email address
@blasern | #1155 | Missing from GitHub contributors page due to (TBC) invalid format email address
@chenghlee | #1457 | Makevars is a script in the package and should not have been excluded

Please read #2456.  If you approve of the license change, please add a review approving this retrospective PR. You are approving both the license change and adding your names to DESCRIPTION. Please also add an approving review to #2456 if GitHub will let you (I don't know if GitHub will let you add approvals to merged PRs).

If you disagree with the license change please reply here, add a review which rejects this PR, or let me know on email and we can discuss further.

Many thanks, and I'm sorry you were not properly credited before.

Best, Matt

### CODE REVIEW

**Comment by dselivanov** [comment]
Thanks @mattdowle, I'm approving.

**Comment by mattdowle** [comment]
Thanks @dselivanov, and thanks for bringing it to our attention. Please click the Files Changed tab and then Review Changes button, and then approve that way please. Hoping for 4 ticks in the top right under reviewers.

**Comment by mattdowle** [comment]
@chenghlee many thanks, I saw your approval on the original PR 2456. Please could you add your approval to this PR as well. Please click the Files Changed tab and then Review Changes button, and then approve. Hoping for 4 ticks in the top right under reviewers.

**Comment by mattdowle** [comment]
Hi @cooldome, did you see this PR?  Waiting for you to approve please before I can merge.

**Comment by cooldome** [comment]
Approved

**Pull request merged**
