### PR TITLE
Simplified isoweek, #2407 #2421

### PR DESCRIPTION
**Pull request by mattdowle**
Follow up on #2407 and #2421 
Tests 1702.1 and 1702.3 failed on win-builder, because of win-builder running in Germany in a different timezone.  They will have failed depending on time of day running the test.
Perplexed as to why `isoweek` used `POSIXlt` in the first place. Further, why it had any time zone usage at all. Probably a hangover from years back. Replaced with simpler integer days from the 1 Jan 1970 epoch (a Thursday, conveniently).

Will create another issue to purge all usage of POSIXlt (still seems much usage in IDateTime.R) and add a grep to CRAN_Release.cmd to catch any usage in future.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
Nice. IIRC I was just mirroring `lubridate::isoweek` and used `POSIXlt` as they did. Not sure why I didn't try harder to skip it. Lazy coding 😱  -- we have our own `wday` function.

Timezone consideration was only added recently due to rounding issues, and those are only introduced (IIUC) because of the `POSIXlt` call.

**Comment by MichaelChirico** [comment]
I'm also noticing a new formula on the Wiki page that looks even easier:

https://en.wikipedia.org/wiki/ISO_week_date#Calculating_the_week_number_of_a_given_date

**Comment by mattdowle** [comment]
Yeah that POSIXlt has been there a long time I think; all usage needs to be purged. That last formula from wikipedia looks about the same complexity to me.  More beneficial would be to do it in C as all those vector ops are allocating each time.  At least it'll now be better than (truly awful) 40 byte POSIXlt.

**Comment by MichaelChirico** [comment]
Agreed. Looks more concise, but actually implementing it is a bear & probably much slower.

I ran the following to be more confident we're not missing anything:

```
date_range = seq.Date(as.Date('1850-01-01'), as.Date('2250-01-01'), by = 'day')

sum(lubridate::isoweek(date_range) != data.table::isoweek(date_range))
```

Included a 1% sample of this since I guess adding 140000-row test is overkill.

**Comment by mattdowle** [comment]
NB: was confused as to coverage fail but it's just that test() has been strengthened and its branches that happen on error aren't being tested, because all tests are passing.

**Comment by mattdowle** [comment]
Great test @MichaelChirico!

**Comment by MichaelChirico** [comment]
re:codecov -- is it overkill to include a meta-test testing `test` 🤔

**Comment by MichaelChirico** [comment]
Also ran this to check there's nothing wrong with `POSIXct` either (there shouldn't be, so not adding another test -- `POSIXct` is covered in 1702.3):

```
#12622694400 is the length in seconds of a 400-year cycle
posix_range = as.POSIXct(sample(12622694400, 1e6), origin = '1970-01-01 00:00:00 UTC')

sum(lubridate::isoweek(posix_range) != data.table::isoweek(posix_range))
# [1] 0
```

**Comment by mattdowle** [comment]
A meta-test testing `test()` is a good idea.  Trouble is how to test it, as inside `test()` it logs the test number for the summary inside the final `stop()` at the end.  If there's a way, it would be good, though.

**Pull request merged**
