### PR TITLE
Refactor internal helpers which generate fragmented messages

### PR DESCRIPTION
**Pull request by MichaelChirico**
Noted in #6532. We should also address the `group.desc` issue, but in principle this PR could be submitted first. cc @aitap

### CODE REVIEW

**Review by tdhock — APPROVED** [review]
helper function duplicated_values looks ok.
I think we should remove group.desc argument, and add a new argument, `called.from.measure` default FALSE.
* If TRUE then we use stopf("... arguments to measure should be uniquely named, problems: %s")
* If FALSE then we use stopf("elements of fun.list should be uniquely named, problems: %s")
or is there some better way of handling the translation issue?

**Comment by MichaelChirico** [comment]
I went with "just drop `group.desc` altogether", I think the error will be clear enough. `measurev()` is mentioned, which is documented next to `measure()` with the argument `fun.list`. If we really wanted to keep the distinction, I'd suggest looking at `sys.calls()` or something like that, rather than adding a new argument which is kind of useless when `measurev()` is exported.

**Comment by tdhock** [comment]
yes that is a good point that we shouldn't be adding arguments that the user can not provide

**Comment by MichaelChirico** [comment]
OK, I'll merge here. If we decide to decide internally that parent is `...` and change the message, we can do so as a follow-up :)

**Pull request merged**
